:
: autogenerated vcproj of Qt put result into \_Oda\Qt\qt\lib
: (after DESTDIR inside installed pro files)
:
: We shoul copy it to DD destination folder
:

:@echo off

if "%ODADIR%"=="" set ODADIR=\_Oda\trunk
if "%QTDIR%"=="" set QTDIR=C:\Qt\2010.05\qt

if not "%ODACFG%"=="" goto end_def_ODACFG
if exist %ODADIR%\exe\vc8dlldbg\OdaMfcApp.exe set ODACFG=vc8dll
if exist %ODADIR%\exe\vc9dlldbg\OdaMfcApp.exe set ODACFG=vc9dll
if exist %ODADIR%\exe\vc10dlldbg\OdaMfcApp.exe set ODACFG=vc10dll
if exist %ODADIR%\exe\vc12dlldbg\OdaMfcApp.exe set ODACFG=vc12dll
:end_def_ODACFG

if "%BINSRC%"=="" set BINSRC=%QTDIR%\bin_%ODACFG%dbg
if "%LIBSRC%"=="" set LIBSRC=%QTDIR%\lib_%ODACFG%dbg
if "%BINDEST%"=="" set BINDEST=%ODADIR%\exe\%ODACFG%dbg
if "%LIBDEST%"=="" set LIBDEST=%ODADIR%\lib\%ODACFG%dbg

:pushd %QTDIR%\lib

if not exist %BINDEST% mkdir %BINDEST%
if not exist %LIBDEST% mkdir %LIBDEST%

: QtMaind.lib QtCored4.dll QtGuid4.dll QtOpenGLd4.dll QtScriptd4.dll QtXmld4.dll : QtNetworkd4.dll 

xcopy /Y %LIBSRC%\QtMaind.lib %LIBDEST%\*.* >nul:
xcopy /Y %LIBSRC%\QtCored4.lib %LIBDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtCored4.dll %BINDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtCored4.pdb %BINDEST%\*.* >nul:
xcopy /Y %LIBSRC%\QtGuid4.lib %LIBDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtGuid4.dll %BINDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtGuid4.pdb %BINDEST%\*.* >nul:
xcopy /Y %LIBSRC%\QtOpenGLd4.lib %LIBDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtOpenGLd4.dll %BINDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtOpenGLd4.pdb %BINDEST%\*.* >nul:
xcopy /Y %LIBSRC%\QtScriptd4.lib %LIBDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtScriptd4.dll %BINDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtScriptd4.pdb %BINDEST%\*.* >nul:
xcopy /Y %LIBSRC%\QtXmld4.lib %LIBDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtXmld4.dll %BINDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtXmld4.pdb %BINDEST%\*.* >nul:
if exist %LIBSRC%\QtNetworkd4.lib xcopy /Y %LIBSRC%\QtNetworkd4.lib %LIBDEST%\*.* >nul:
if exist %BINSRC%\QtNetworkd4.dll xcopy /Y %BINSRC%\QtNetworkd4.dll %BINDEST%\*.* >nul:
if exist %BINSRC%\QtNetworkd4.pdb xcopy /Y %BINSRC%\QtNetworkd4.pdb %BINDEST%\*.* >nul:


:popd 
