:
: autogenerated vcproj of Qt put result into \_Oda\Qt\qt\lib
: (after DESTDIR inside installed pro files)
:
: We shoul copy it to DD destination folder
:

:@echo off

if "%ODADIR%"=="" set ODADIR=\_Oda\trunk

if not "%ODACFG%"=="" goto end_def_ODACFG
if exist %ODADIR%\exe\vc8dll\OdaMfcApp.exe set ODACFG=vc8dll
if exist %ODADIR%\exe\vc9dll\OdaMfcApp.exe set ODACFG=vc9dll
if exist %ODADIR%\exe\vc10dll\OdaMfcApp.exe set ODACFG=vc10dll
if exist %ODADIR%\exe\vc12dll\OdaMfcApp.exe set ODACFG=vc12dll
:end_def_ODACFG

if exist %ODADIR%\exe\vc8dll\OdaMfcApp.exe set CGLIB=%ODADIR%\Caustic\OpenRL\ThirdParty\OpenRL_SDK\Lib\VisualStudio8\Win32
if exist %ODADIR%\exe\vc9dll\OdaMfcApp.exe set CGLIB=%ODADIR%\Caustic\OpenRL\ThirdParty\OpenRL_SDK\Lib\VisualStudio9\Win32
if exist %ODADIR%\exe\vc10dll\OdaMfcApp.exe set CGLIB=%ODADIR%\Caustic\OpenRL\ThirdParty\OpenRL_SDK\Lib\VisualStudio10\Win32
if exist %ODADIR%\exe\vc12dll\OdaMfcApp.exe set CGLIB=%ODADIR%\Caustic\OpenRL\ThirdParty\OpenRL_SDK\Lib\VisualStudio12\Win32

pushd %ODADIR%\Caustic\Bin\OpenRL_SDK\Bin\Win32\Release

set BINDEST=%ODADIR%\exe\%ODACFG%
if not exist %BINDEST% mkdir %BINDEST%

xcopy /Y CausticGLUT.dll %BINDEST%\*.* >nul:
xcopy /Y OpenRL.dll %BINDEST%\*.* >nul:
xcopy /Y pthreadVC2.dll %BINDEST%\*.* >nul:

set LIBDEST=%ODADIR%\lib\%ODACFG%
if not exist %LIBDEST% mkdir %LIBDEST%

xcopy /Y %CGLIB%\CausticGLUT.lib %LIBDEST%\*.* >nul:
xcopy /Y %CGLIB%\OpenRL.lib %LIBDEST%\*.* >nul:

popd 

