:
: autogenerated vcproj of Qt put result into \_Oda\Qt\qt\lib
: (after DESTDIR inside installed pro files)
:
: We shoul copy it to DD destination folder
:

:@echo off

if "%ODADIR%"=="" set ODADIR=\_Oda\trunk
if "%QTDIR%"=="" set QTDIR=C:\Qt\2010.05\qt

if not "%ODACFG%"=="" goto end_def_ODACFG
if exist %ODADIR%\exe\vc8dll\OdaMfcApp.exe set ODACFG=vc8dll
if exist %ODADIR%\exe\vc9dll\OdaMfcApp.exe set ODACFG=vc9dll
if exist %ODADIR%\exe\vc10dll\OdaMfcApp.exe set ODACFG=vc10dll
if exist %ODADIR%\exe\vc12dll\OdaMfcApp.exe set ODACFG=vc12dll
:end_def_ODACFG

if "%BINSRC%"=="" set BINSRC=%QTDIR%\bin_%ODACFG%
if "%LIBSRC%"=="" set LIBSRC=%QTDIR%\lib_%ODACFG%
if "%BINDEST%"=="" set BINDEST=%ODADIR%\exe\%ODACFG%
if "%LIBDEST%"=="" set LIBDEST=%ODADIR%\lib\%ODACFG%

:pushd %QTDIR%\lib

if not exist %BINDEST% mkdir %BINDEST%
if not exist %LIBDEST% mkdir %LIBDEST%

: QtMain.lib QtCore4.dll QtGui4.dll QtOpenGL4.dll QtScript4.dll QtXml4.dll : QtNetwork4.dll 

xcopy /Y %LIBSRC%\QtMain.lib %LIBDEST%\*.* >nul:
xcopy /Y %LIBSRC%\QtCore4.lib %LIBDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtCore4.dll %BINDEST%\*.* >nul:
xcopy /Y %LIBSRC%\QtGui4.lib %LIBDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtGui4.dll %BINDEST%\*.* >nul:
xcopy /Y %LIBSRC%\QtOpenGL4.lib %LIBDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtOpenGL4.dll %BINDEST%\*.* >nul:
xcopy /Y %LIBSRC%\QtScript4.lib %LIBDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtScript4.dll %BINDEST%\*.* >nul:
xcopy /Y %LIBSRC%\QtXml4.lib %LIBDEST%\*.* >nul:
xcopy /Y %BINSRC%\QtXml4.dll %BINDEST%\*.* >nul:
if exist %LIBSRC%\QtNetwork4.lib xcopy /Y %LIBSRC%\QtNetwork4.lib %LIBDEST%\*.* >nul:
if exist %BINSRC%\QtNetwork4.dll xcopy /Y %BINSRC%\QtNetwork4.dll %BINDEST%\*.* >nul:

:popd

