/////////////////////////////////////////////////////////////////////////////// 
// Copyright (C) 2002-2020, Open Design Alliance (the "Alliance"). 
// All rights reserved. 
// 
// This software and its documentation and related materials are owned by 
// the Alliance. The software may only be incorporated into application 
// programs owned by members of the Alliance, subject to a signed 
// Membership Agreement and Supplemental Software License Agreement with the
// Alliance. The structure and organization of this software are the valuable  
// trade secrets of the Alliance and its suppliers. The software is also 
// protected by copyright law and international treaty provisions. Application  
// programs incorporating this software must include the following statement 
// with their copyright notices:
//   
//   This application incorporates Open Design Alliance software pursuant to a license 
//   agreement with Open Design Alliance.
//   Open Design Alliance Copyright (C) 2002-2020 by Open Design Alliance. 
//   All rights reserved.
//
// By use of this software, its documentation or related materials, you 
// acknowledge and accept the above terms.
///////////////////////////////////////////////////////////////////////////////
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opendesign_odaandroiddgnapp_TeighaDGNJni */

#ifndef _Included_com_opendesign_odaandroiddgnapp_TeighaDGNJni
#define _Included_com_opendesign_odaandroiddgnapp_TeighaDGNJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opendesign_odaandroiddgnapp_TeighaDGNJni
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_odaandroiddgnapp_TeighaDGNJni_init
  (JNIEnv *, jclass);

/*
 * Class:     com_opendesign_odaandroiddgnapp_TeighaDGNJni
 * Method:    finit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_odaandroiddgnapp_TeighaDGNJni_finit
  (JNIEnv *, jclass);

/*
 * Class:     com_opendesign_odaandroiddgnapp_TeighaDGNJni
 * Method:    open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_odaandroiddgnapp_TeighaDGNJni_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_opendesign_odaandroiddgnapp_TeighaDGNJni
 * Method:    createRenderer
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_odaandroiddgnapp_TeighaDGNJni_createRenderer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_opendesign_odaandroiddgnapp_TeighaDGNJni
 * Method:    renderFrame
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_odaandroiddgnapp_TeighaDGNJni_renderFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_opendesign_odaandroiddgnapp_TeighaDGNJni
 * Method:    destroyRenderer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_odaandroiddgnapp_TeighaDGNJni_destroyRenderer
  (JNIEnv *, jclass);

/*
 * Class:     com_opendesign_odaandroiddgnapp_TeighaDGNJni
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_odaandroiddgnapp_TeighaDGNJni_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
