{
   "description": "This file is generated by qmake to be read by androiddeployqt and should not be modified by hand.",
   "qt": "@QTDIR_PATH@",
   "sdk": "@ANDROID_SDK@",
   "ndk": "@ANDROID_NDK@",
   "toolchain-prefix": "arm-linux-androideabi",
   "tool-prefix": "arm-linux-androideabi",
   "toolchain-version": "4.8",
   "ndk-host": "windows",
   "target-architecture": "@ODA_ANDROID_ARCH@",
   "android-package-source-directory": "@CMAKE_CURRENT_SOURCE_DIR@/data/android-sources",
   "application-binary": "@ODA_BIN_DIR@/libOdaFileConverter.so"
}
