/////////////////////////////////////////////////////////////////////////////// 
// Copyright (C) 2002-2022, Open Design Alliance (the "Alliance"). 
// All rights reserved. 
// 
// This software and its documentation and related materials are owned by 
// the Alliance. The software may only be incorporated into application 
// programs owned by members of the Alliance, subject to a signed 
// Membership Agreement and Supplemental Software License Agreement with the
// Alliance. The structure and organization of this software are the valuable  
// trade secrets of the Alliance and its suppliers. The software is also 
// protected by copyright law and international treaty provisions. Application  
// programs incorporating this software must include the following statement 
// with their copyright notices:
//   
//   This application incorporates Open Design Alliance software pursuant to a license 
//   agreement with Open Design Alliance.
//   Open Design Alliance Copyright (C) 2002-2022 by Open Design Alliance. 
//   All rights reserved.
//
// By use of this software, its documentation or related materials, you 
// acknowledge and accept the above terms.
///////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////
// return codes definition container

//        Code                Message string
OD_TV_RETCODE_DEF( tvOk,                OD_T("All is OK"))
OD_TV_RETCODE_DEF( tvInternal,          OD_T("Internal error"))
OD_TV_RETCODE_DEF( tvNotImplementedYet, OD_T("Not implemented yet"))
OD_TV_RETCODE_DEF( tvNotSupported,      OD_T("Not supported"))
OD_TV_RETCODE_DEF( tvInvalidInput,      OD_T("Input parameters are invalid"))
OD_TV_RETCODE_DEF( tvFactoryDoesntExist, OD_T("The factory object doesn't exist"))
OD_TV_RETCODE_DEF( tvMissingObject,     OD_T("The requested object is missed"))
OD_TV_RETCODE_DEF( tvObjectLeftOnDisk,  OD_T("A needed object is left on disk"))
OD_TV_RETCODE_DEF( tvErasedObject,      OD_T("The requested object was erased"))
OD_TV_RETCODE_DEF( tvIdHasNoData,       OD_T("Id has no data"))
OD_TV_RETCODE_DEF( tvIdWrongData,       OD_T("Id has wrong data"))
OD_TV_RETCODE_DEF( tvIdWrongDataType,   OD_T("Id data has wrong type"))
OD_TV_RETCODE_DEF( tvNullObjectPtr,     OD_T("Null object's pointer"))
OD_TV_RETCODE_DEF( tvAlreadyExistSameName,     OD_T("Object with the same name already exist"))
OD_TV_RETCODE_DEF( tvGeometryDataDoesntExistOrBeenDeleted,     OD_T("Geometry data doesn't exist or been deleted"))
OD_TV_RETCODE_DEF( tvGeometryDataHasAnotherType,     OD_T("Geometry data has another type than was asked"))
OD_TV_RETCODE_DEF( tvWrongDevicePathData,                 OD_T("It is imposible to define the device module loading path"))
OD_TV_RETCODE_DEF( tvDeviceLoadingFailed,                 OD_T("It is imposible to load the device module"))
OD_TV_RETCODE_DEF( tvDeviceCreatingFailed,                OD_T("Device creation failed"))
OD_TV_RETCODE_DEF( tvDeviceWrongType,                     OD_T("Wrong device type"))
OD_TV_RETCODE_DEF( tvDeviceWrongBitmapState,              OD_T("Trying to setup the bitmap device as non-bitmap or vice versa"))
OD_TV_RETCODE_DEF( tvInvaliedDeviceOption,                OD_T("Invalid device option"))
OD_TV_RETCODE_DEF( tvDeviceOptionHasErrorType,            OD_T("Device option has error type"))
OD_TV_RETCODE_DEF( tvDeviceOptionDoesntSupport,           OD_T("Device option doesn't support"))
OD_TV_RETCODE_DEF( tvDevicesIsEmpty,                      OD_T("There is no devices in the database"))
OD_TV_RETCODE_DEF( tvViewHasDifferentDevice,              OD_T("The associated with the view and the current devices are different"))
OD_TV_RETCODE_DEF( tvViewIndexTooBig,                     OD_T("The view index is too big (greater than the number of views)"))
OD_TV_RETCODE_DEF( tvViewIndexTooSmall,                   OD_T("The view index is too small (less than zero)"))
OD_TV_RETCODE_DEF( tvModelHasErrorDatabase,               OD_T("The model has different databases with the device"))
OD_TV_RETCODE_DEF( tvMethodNotImplemented,                OD_T("Method not implemented in the internal object"))
OD_TV_RETCODE_DEF( tvGeoDataHasNoParent,                  OD_T("Geometrical object has no parent data. May be internal error"))
OD_TV_RETCODE_DEF( tvCannotCreateInternalDatabase,        OD_T("Error occus during the creating of the internal database"))
OD_TV_RETCODE_DEF( tvInternalDeviceDoesntCreated,         OD_T("Internal Gs device doesn't created yet"))
OD_TV_RETCODE_DEF( tvMissedTextTraits,                    OD_T("There is no text traits. Text entity can not be created"))
OD_TV_RETCODE_DEF( tvInternalDatabaseDoesntCreated,       OD_T("Internal database doesn't created yet"))
OD_TV_RETCODE_DEF( tvPolygonNotPlanar,                    OD_T("The incoming polygon is not planar"))
OD_TV_RETCODE_DEF( tvPolygonHasLessThanThreePoints,       OD_T("The incoming polygon has less than 3 points"))
OD_TV_RETCODE_DEF( tvInternalDatabaseHasNoModelsContainer, OD_T("The internal database has empty models container"))
OD_TV_RETCODE_DEF( tvInternalDatabaseHasNoImagesContainer, OD_T("The internal database has empty images container"))
OD_TV_RETCODE_DEF( tvInternalDatabaseHasNoVisualStylesContainer, OD_T("The internal database has empty visual styles container"))
OD_TV_RETCODE_DEF( tvInternalIteratorMissing,              OD_T("The internal iterator is missing"))
OD_TV_RETCODE_DEF( tvLinearlyDependentCircleArg,           OD_T("The input circle arguments are linearly dependent."))
OD_TV_RETCODE_DEF( tvEmptyName,                            OD_T("Empty name"))
OD_TV_RETCODE_DEF( tvInvalidName,                          OD_T("Invalid name"))
OD_TV_RETCODE_DEF( tvForbiddenName,                        OD_T("Forbidden name"))
OD_TV_RETCODE_DEF( tvSelfReferencedBlock,                  OD_T("It is impossible to create self-referenced blocks"))
OD_TV_RETCODE_DEF( tvInvalidColorType,                     OD_T("Wrong color type"))
OD_TV_RETCODE_DEF( tvInvalidLinetypeType,                  OD_T("Invalid linetype type"))
OD_TV_RETCODE_DEF( tvNonPositiveNurbsDegree,               OD_T("Non positive degree of the NURBS"))
OD_TV_RETCODE_DEF( tvInvalidNurbsControlPoints,            OD_T("A NURBS curve has invalid control points"))
OD_TV_RETCODE_DEF( tvInvalidNurbsWeights,                  OD_T("A NURBS curve has invalid weights"))
OD_TV_RETCODE_DEF( tvInvalidNurbsKnots,                    OD_T("A NURBS curve has invalid knots"))
OD_TV_RETCODE_DEF( tvInvalidNurbsStartEndParams,           OD_T("A NURBS curve has invalid start and/or end parameter values"))
OD_TV_RETCODE_DEF( tvNotOpenForWrite,                      OD_T("The object is closed for writing"))
OD_TV_RETCODE_DEF( tvInvalidLineWeightType,                OD_T("Invalid type of lineweight"))
OD_TV_RETCODE_DEF( tvImageFileAccessErr,                   OD_T("Image file access error"))
OD_TV_RETCODE_DEF( tvImageNotLoaded,                       OD_T("Image file not loaded"))
OD_TV_RETCODE_DEF( tvInvalidLayerType,                     OD_T("Invalid layer type"))
OD_TV_RETCODE_DEF( tvRasterImageObjectDoesntExistOrBeenDeleted, OD_T("Raster image object doesn't exist or been deleted"))
OD_TV_RETCODE_DEF( tvInvalidVerticesInput,                 OD_T("Invalid input vertex data was provided"))
OD_TV_RETCODE_DEF( tvInvalidFacesInput,                    OD_T("Invalid input face data was provided"))
OD_TV_RETCODE_DEF( tvInvalidShellVerticesInput,            OD_T("Invalid vertices data for the shell object"))
OD_TV_RETCODE_DEF( tvInvalidShellFacesInput,               OD_T("Invalid faces data for the shell object"))
OD_TV_RETCODE_DEF( tvInvalidMeshVerticesInput,             OD_T("Invalid vertices data for the mesh object"))
OD_TV_RETCODE_DEF( tvInvalidTransparencyType,              OD_T("Invalid transparency type"))
OD_TV_RETCODE_DEF( tvNonSetupDevice,                       OD_T("The device is not setuped"))
OD_TV_RETCODE_DEF( tvEmptyFilePath,                        OD_T("Invalid file path"))
OD_TV_RETCODE_DEF( tvMissingFilerModule,                   OD_T("It is not possible to download the tv database filer module"))
OD_TV_RETCODE_DEF( tvMissinFiler,                          OD_T("It is not possible to get the filer object from filer module"))
OD_TV_RETCODE_DEF( tvInvalidFilePath,                      OD_T("Invalid file path"))
OD_TV_RETCODE_DEF( tvCannotOpenFile,                       OD_T("It is not possible to open the file"))
OD_TV_RETCODE_DEF( tvErrorDuringOpenFile,                  OD_T("Errors ocurs during file opening"))
OD_TV_RETCODE_DEF( tvFilerEmptyInternalDatabase,           OD_T("The database is empty after reading inside the filer"))
OD_TV_RETCODE_DEF( tvMissingVisualizeDevice,               OD_T("The visualize device module is missing"))
OD_TV_RETCODE_DEF( tvWrongRasterImageType,                 OD_T("Wrong raster image format. Binary while called method for the file based and vice versa"))
OD_TV_RETCODE_DEF( tvInvalidFileType,                      OD_T("Unsupported file type."))
OD_TV_RETCODE_DEF( tvViewportObjectCanHaveOnlyOneParent,   OD_T("Viewport object can have only one parent view."))
OD_TV_RETCODE_DEF( tvThereIsNoActiveView,                  OD_T("There is no active view."))
OD_TV_RETCODE_DEF( tvInvalidClippingPointInput,            OD_T("Invalid clipping point input."))
OD_TV_RETCODE_DEF( tvWrongHandledObjectClass,              OD_T("Wrong handled object class."))
OD_TV_RETCODE_DEF( tvWrongHandledObjectParent,             OD_T("Wrong handled object parent."))
OD_TV_RETCODE_DEF( tvWrongHandledObjectType,               OD_T("Wrong handled object type."))
OD_TV_RETCODE_DEF( tvDuplicateHandle,                      OD_T("Handle already exist."))
OD_TV_RETCODE_DEF( tvWrongSubItemPath,                     OD_T("Wrong subitem path."))
OD_TV_RETCODE_DEF( tvInvalidExtents,                       OD_T("Invalid extents."))
OD_TV_RETCODE_DEF( tvNoRequestedExtents,                   OD_T("There are no requested extents."))
OD_TV_RETCODE_DEF( tvOperationIsNotAllowedBy2dView,        OD_T("This operation is not allowed by view in 2d mode"))
OD_TV_RETCODE_DEF( tvInvalidVisualStyleOption,             OD_T("Invalid visual style option"))
OD_TV_RETCODE_DEF( tvVisualStyleOptionHasErrorType,        OD_T("Visual style option has error type"))
OD_TV_RETCODE_DEF( tvForbiddenOperationDefVisualStyle,     OD_T("This operation is not allowed for the default visual style"))
OD_TV_RETCODE_DEF( tvInvalidBoxVectors,                    OD_T("Invalid input vectors for the box creation"))
OD_TV_RETCODE_DEF( tvErrorDuringExport,                    OD_T("An error occurred while exporting database to specified file"))
OD_TV_RETCODE_DEF( tvMissingExportModule,                  OD_T("A export module is missing"))
OD_TV_RETCODE_DEF( tvMissingExporter,                      OD_T("A exporter is missing"))
OD_TV_RETCODE_DEF( tvNonRevisionControlInternalDatabase,   OD_T("Internal database has no storage"))
OD_TV_RETCODE_DEF( tvOkOldFormatRead,                      OD_T("Old file format readed successfully"))
OD_TV_RETCODE_DEF( tvMissingModelerGeometryCreatorService, OD_T("The modeler geometry creator service is missing"))
OD_TV_RETCODE_DEF( tvBrepBuilderInitializationFailed,      OD_T("The Brep builder initialization was failed"))
OD_TV_RETCODE_DEF( tvMissingBrepFilerModule,               OD_T("The Brep builder module is missing"))
OD_TV_RETCODE_DEF( tvBrepBuilderConversionFailed,          OD_T("The Brep builder conversion was failed"))
OD_TV_RETCODE_DEF( tvBrepBuilderFinishFailed,              OD_T("The Brep builder fininsh process was failed"))
OD_TV_RETCODE_DEF( tvBrepHasNoCache,                       OD_T("The Brep data has no cache"))
OD_TV_RETCODE_DEF( tvCollideWarnInputHasInvalidData,       OD_T("Collide warning: input contains invalid data"))
OD_TV_RETCODE_DEF( tvCollideErrorInputHasNoValidData,      OD_T("Collide error: input has no valid data"))
OD_TV_RETCODE_DEF( tvCollideWarnInputWithHasInvalidData,   OD_T("Collide warning: collide with contains invalid data"))
OD_TV_RETCODE_DEF( tvCollideWarnInputWithHasNoValidData,   OD_T("Collide warning: collide with has no valid data"))
OD_TV_RETCODE_DEF( tvCollideSelectionLevelWasChanged,      OD_T("Collide warning: selection level was changed (from nested to entity)")) 
OD_TV_RETCODE_DEF( tvPolylineHasNoPoints,                  OD_T("A polyline has no points"))
OD_TV_RETCODE_DEF( tvZeroNormal,                           OD_T("A normal vector has invalid value"))
OD_TV_RETCODE_DEF( tvEllipseInvalidPoints,                 OD_T("An ellipse has invalid points"))
OD_TV_RETCODE_DEF( tvSphereZeroBasis,                      OD_T("A sphere vectors (axis/prime meridian) is/are zero length"))
OD_TV_RETCODE_DEF( tvCylinderMatchingPoints,               OD_T("A cylinder has matching points"))
OD_TV_RETCODE_DEF( tvCylinderPointsNumber,                 OD_T("A cylinder points number is invalid"))
OD_TV_RETCODE_DEF( tvCylinderRadiiNumber,                  OD_T("A cylinder radii number is invalid"))
OD_TV_RETCODE_DEF( tvInfiniteLineMatchingPoints,           OD_T("An infinite line/ray  has matching points"))
OD_TV_RETCODE_DEF( tvRasterImageZeroVector,                OD_T("A raster image has zero vectors"))
OD_TV_RETCODE_DEF( tvCollisionResultsHaveNotEqualLenth,    OD_T("A lists with result of collision have different length"))
OD_TV_RETCODE_DEF( tvCuttingPlaneZeroNormal,               OD_T("A cutting plane function has zero length normal"))
OD_TV_RETCODE_DEF( tvRcsModuleIsMissed,                    OD_T("The Rcs modules is missed"))
OD_TV_RETCODE_DEF( tvNativePropMissedDatabase,             OD_T("The database for the manipulation with nateive properties is missed"))
OD_TV_RETCODE_DEF( tvNativePropMissedObject,               OD_T("An object for the manipulation with nateive properties is missed"))
OD_TV_RETCODE_DEF( tvWarning,                              OD_T("No error occurred, but some functionality may not work"))
OD_TV_RETCODE_DEF( tvCommonDataAccessTreeMissed,           OD_T("Common data access tree is missed"))
OD_TV_RETCODE_DEF( tvProgressiveMeshWasNotObtained,        OD_T("Failed to retrieve progressive mesh traits"))
OD_TV_RETCODE_DEF( tvEntityIdNotFoundForOriginal,          OD_T("Failed to find entity by original id"))
OD_TV_RETCODE_DEF( tvPointCloudDoesNotHaveRequestedData,   OD_T("Point cloud does not have requested data"))
OD_TV_RETCODE_DEF( tvFilerEmptyContext,                    OD_T("Data context could not be obtained"))
OD_TV_RETCODE_DEF( tvUserAbort,                            OD_T("Operation aborted by user"))
OD_TV_RETCODE_DEF( tvAlreadyInUse,                         OD_T("Trying to modify data that is already in use"))
OD_TV_RETCODE_DEF( tvIsolateHideNoGsNode,                  OD_T("Trying to /per session/ isolate/hide data without Gs cache"))
OD_TV_RETCODE_DEF( tvOkPartially,                          OD_T("An operation successfully finished partially"))
OD_TV_RETCODE_DEF( tvForbiddenOperationDefHighlightStyle,  OD_T("A forbidden highlight style operation was requested"))
