/////////////////////////////////////////////////////////////////////////////// 
// Copyright (C) 2002-2022, Open Design Alliance (the "Alliance"). 
// All rights reserved. 
// 
// This software and its documentation and related materials are owned by 
// the Alliance. The software may only be incorporated into application 
// programs owned by members of the Alliance, subject to a signed 
// Membership Agreement and Supplemental Software License Agreement with the
// Alliance. The structure and organization of this software are the valuable  
// trade secrets of the Alliance and its suppliers. The software is also 
// protected by copyright law and international treaty provisions. Application  
// programs incorporating this software must include the following statement 
// with their copyright notices:
//   
//   This application incorporates Open Design Alliance software pursuant to a license 
//   agreement with Open Design Alliance.
//   Open Design Alliance Copyright (C) 2002-2022 by Open Design Alliance. 
//   All rights reserved.
//
// By use of this software, its documentation or related materials, you 
// acknowledge and accept the above terms.
///////////////////////////////////////////////////////////////////////////////
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opendesign_android_TeighaDWGJni */

#ifndef _Included_com_opendesign_android_TeighaDWGJni
#define _Included_com_opendesign_android_TeighaDWGJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opendesign_android_TeighaDWGJni
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_init
  (JNIEnv *, jclass);

/*
 * Class:     com_opendesign_android_TeighaDWGJni
 * Method:    finit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_finit
   (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_open
  (JNIEnv *, jclass, jstring);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_renderFrame
  (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_viewTranslate
  (JNIEnv *, jclass, jfloat, jfloat);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_viewScale
  (JNIEnv *, jclass, jfloat);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_viewOrbit
  (JNIEnv *, jclass, jfloat, jfloat);
  
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_viewRotate
  (JNIEnv *, jclass, jfloat);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_setVisualStyle
  (JNIEnv *, jclass, jstring);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_setRenderMode
  (JNIEnv *, jclass, jstring);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_setViewPosition
  (JNIEnv *, jclass, jint);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_zoomWindow
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_zoomExtents
  (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_startSelectionFrame
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_resizeSelectionFrame
  (JNIEnv *, jclass, jint, jint);
  
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_setProjectionForActiveView
  (JNIEnv *, jclass, jint)

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_createObjectExplorer
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_opendesign_android_TeighaDWGJni_getChildrenCount
  (JNIEnv *, jclass, jint)

JNIEXPORT jint JNICALL Java_com_opendesign_android_TeighaDWGJni_toParent
  (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_toChild
  (JNIEnv *, jclass, jint)

JNIEXPORT jobjectArray JNICALL Java_com_opendesign_android_TeighaDWGJni_getCurrentObjects
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
