/////////////////////////////////////////////////////////////////////////////// 
// Copyright (C) 2002-2022, Open Design Alliance (the "Alliance"). 
// All rights reserved. 
// 
// This software and its documentation and related materials are owned by 
// the Alliance. The software may only be incorporated into application 
// programs owned by members of the Alliance, subject to a signed 
// Membership Agreement and Supplemental Software License Agreement with the
// Alliance. The structure and organization of this software are the valuable  
// trade secrets of the Alliance and its suppliers. The software is also 
// protected by copyright law and international treaty provisions. Application  
// programs incorporating this software must include the following statement 
// with their copyright notices:
//   
//   This application incorporates Open Design Alliance software pursuant to a license 
//   agreement with Open Design Alliance.
//   Open Design Alliance Copyright (C) 2002-2022 by Open Design Alliance. 
//   All rights reserved.
//
// By use of this software, its documentation or related materials, you 
// acknowledge and accept the above terms.
///////////////////////////////////////////////////////////////////////////////
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OdaDgnApp.rc
//
#define IDOK2                           2
#define IDC_DELETE                      3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ERASE_REQUEST               101
#define IDD_ODADGNTREEVIEW              103
#define IDR_MAINFRAME                   128
#define IDR_ODADGNAPPTYPE               129
#define IDR_TREEVIEW_MENU               130
#define IDR_VECTORIZER                  140
#define IDD_LOAD_APPS                   141
#define IDD_LOAD_APPS2                  142
#define IDD_SOLID_HELPER_PAGE1          144
#define IDD_SYMBRSRC                    145
#define IOD_TRIANG_DIALOG               148
#define IDD_PDFEXPORT                   149
#define IDD_STATIC_APPS                 150
#define IDD_SOLID_HELPER_PAGE2          151
#define IDD_SOLID_HELPER_PAGE3          152
#define IDD_SOLID_HELPER_PAGE4          153
#define IDD_RSRC                        154
#define IDD_FASTFONT                    155
#define IDD_FIND_DLG                    156
#define IDD_STL_EXPORT                  157
#define IDD_CHOSE_MODEL                 158
#define IDD_SUMMINFO                    159
#define IDD_PATTERN                     160
#define IDD_CAMERAVIEW                  161
#define IDD_RENDERING_PROP_DLG          162
#define IDD_CONSOLE_DLG                 163
#define IDD_GRIP_POINTS_PROP_DLG        164
#define IDD_PAGE_SETUP_DLG              165
#define IDD_CELLLIBRARY_PREWIEW         166
#define IDB_TEIGHA_BASE_BMP             167
#define IDD_DIALOG_CUSTOM_PROPERTIES    168
#define IDD_COLOR_BUTTONS               169
#define IDD_COLOR_BUTTONS_DLG           169
#define IDD_LINKS_ATTRS                 170
#define IDR_COLORBUTTON1                172
#define IDD_VIEWFLAGS_DIALOG            177
#define IDR_VECTORIZE_POPUP_MENU        178
#define IDD_FIELD_VIEW                  183
#define IDD_LEVEL_PROPERTIES_COLOR      190
#define IDD_LEVEL_PROPERTIES_LINESTYLE  192
#define IDD_DIALOG_LOAD_LINETYPE        194
#define IDD_PDF_ATTACH_DIALOG           201
#define IDD_BACKGROUND_COLOR            227
#define IDD_RENDER_DBLIGHTS             232
#define IDD_RENDER_DBMATERIALS          234
#define IDD_COMPRESS_DIALOG             235
#define IDD_ITEMTYPE_LIBS               236
#define IDD_ATTACH_ITEMTYPES            237
#define IDB_LAYER_STATES                238
#define IDD_PDF_EXPORT_LAYOUT_VIEWS     239
#define IDD_DIALOG_LINESTYLE_SCALE      240
#define IDD_DIALOG_LINESTYLE_SCALE1     241
#define IDD_DIALOG_XREFMERGE            242
#define IDD_CDA_PROPERTIES              243
#define IDD_CDASTDBTN_DLG               244
#define IDD_CDASTDARRAY_DLG             246
#define IDD_CDASETTRANS_DLG             247
#define IDD_CDAMATCOLOR_DLG             248
#define IDD_CDA_ARRAYPROP               248
#define IDD_CDASETVALUE_DLG1            249
#define IDD_CDA_UNIONTYPE               249
#define IDC_FILE_LIST                   1000
#define IDC_ENTITIES_LIST               1001
#define IDC_GET_PATH                    1002
#define IDC_PATH                        1003
#define IDC_SEARCH                      1004
#define IDC_EDIT1                       1005
#define IDC_ELEMENTDUMPLIST             1006
#define IDC_EDIT_STREAM                 1007
#define IDC_CHECK_SUBFOLDERS            1008
#define IDC_CHECK_DGN                   1009
#define IDC_CHECK_X_B                   1010
#define IDC_CHECK_X_T                   1011
#define IDC_CHECK_SAT                   1012
#define IDC_DGNTREEVIEW                 1013
#define IDC_INF_COPYRIGHT               1014
#define IDC_INF_LIBRARY                 1015
#define IDC_BUTTON_ORIGINAL             1016
#define IDC_SUMMINFO_LIST               1016
#define IDC_CHECK_BINARY                1017
#define IDC_BUTTON3                     1018
#define IDC_BUTTON_COMPARE              1019
#define IDC_BUTTON_SAVE                 1020
#define IDC_EDIT_DEGREE                 1021
#define IDC_BUTTON_LOADFILE             1022
#define IDC_HANDLE                      1023
#define IDC_BUTTON_SAVE2                1024
#define IDC_UNLOAD_APP                  1025
#define IDC_LOAD_APP                    1026
#define IDC_APPS_LIST                   1027
#define IDC_APPLIST                     1028
#define IDC_EDIT_FILE                   1029
#define IDC_EMEDDED                     1030
#define IDC_TTF_AS_GEOM                 1031
#define IDC_SHX_AS_GEOM                 1032
#define IDC_BUTTON_SAVE_LINETYPE        1032
#define IDC_GEOM_OPT                    1033
#define IDC_TITLE                       1034
#define IDC_AUTHOR                      1035
#define IDC_SUBJECT                     1036
#define IDC_KEYWORDS                    1037
#define IDC_CREATOR                     1038
#define IDC_PRODUCER                    1039
#define IDC_EDIT_PAPER_WIDTH            1040
#define IDC_EDIT_PAPER_HEIGHT           1041
#define IDC_RADIO_ACTIVE                1042
#define IDC_RADIO_ALL                   1043
#define IDC_ZOOM                        1044
#define IDC_LIGHTS_LIST                 1044
#define IDC_HLR                         1047
#define IDC_ENCODED                     1048
#define IDC_CHECK_DEBUG                 1049
#define IDC_RADIO_ACTIVE2               1049
#define IDC_PROMPT                      1050
#define IDC_RADIO_ALL2                  1050
#define IDC_LIST2                       1051
#define IDC_HLR2                        1051
#define IDC_RADIO_FENCE                 1051
#define IDC_RADIO_ALL3                  1051
#define IDC_INPUT                       1052
#define IDC_BUTTON2                     1053
#define IDC_BUTTON_DOWN_LINK            1053
#define IDC_DEL_LIB_BUTTON              1053
#define IDC_DETACH_BUTTON               1053
#define IDC_BUTTON_SELECT_VIEWS         1053
#define IDC_VIEWLIST                    1054
#define IDC_DETACH_BUTTON2              1054
#define IDC_OPENLIB_BUTTON              1054
#define IDC_PARALLELRADIO               1055
#define IDC_PROGECTIONRADIO             1056
#define IDC_POSXEDIT                    1057
#define IDC_POSYEDIT                    1058
#define IDC_POSZEDIT                    1059
#define IDC_TARGETXEDIT                 1060
#define IDC_TARGETYEDIT                 1061
#define IDC_YEDIT                       1061
#define IDC_TARGETZEDIT                 1062
#define IDC_ZEDIT                       1062
#define IDC_ORIENTEDIT                  1063
#define IDC_ELEVATEEDIT                 1064
#define IDC_ROLLEDIT                    1065
#define IDC_FOCUSEDIT                   1066
#define IDC_LENSEDIT                    1067
#define IDC_LENSEDIT2                   1068
#define IDC_LENSEDIT3                   1069
#define IDC_CLOSE                       1070
#define IDC_ONRADIO                     1071
#define IDC_OFFRADIO                    1072
#define IDC_GET_DIR                     1073
#define IDC_EXPAND_CLIPPING_PLANES      1073
#define IDC_CLIPFRONTEDIT               1074
#define IDC_CLIPBACKEDIT                1075
#define IDC_NURNS_EDIT                  1076
#define IDC_EDIT_KNOTS                  1077
#define IDC_COMBO1                      1078
#define IDC_BROWSE                      1079
#define IDC_BASE_COMBO                  1080
#define IDC_HOVER_COMBO                 1081
#define IDC_HOT_COMBO                   1082
#define IDC_GRIPOBJLIMIT_EDIT           1083
#define IDC_GRIPSIZE_EDIT               1084
#define IDC_PRINTER_NAME_COMBO          1085
#define IDC_PLOTTER_STATIC              1086
#define IDC_WHERE_STATIC                1087
#define IDC_DESCRIPTION_STATIC          1088
#define IDC_PAPER_COMBO                 1089
#define IDC_PAPER_H_EDIT                1090
#define IDC_MARGIN_L_EDIT               1091
#define IDC_MARGIN_B_EDIT               1092
#define IDC_MARGIN_T_EDIT               1093
#define IDC_MARGIN_R_EDIT               1094
#define IDC_PAPER_W_EDIT                1095
#define IDC_VIEW_COMBO                  1096
#define IDC_VALUE_EDIT                  1096
#define IDC_RENDER_COMBO                1097
#define IDC_PLOT_MODE_COMBO             1098
#define IDC_ROTATION_COMBO              1099
#define IDC_OFFSET_X_EDIT               1100
#define IDC_OFFSET_Y_EDIT               1101
#define IDC_SCALE_EDIT                  1103
#define IDC_BUTTON1                     1104
#define IDC_FILENAME_BUTTON             1104
#define IDC_ADDBUTTON                   1104
#define IDC_CANCEL                      1104
#define IDC_BUTTON_UP_LINK              1104
#define IDC_ADDLIB_BUTTON               1104
#define IDC_ATTACH_BUTTON               1104
#define IDC_UPBUTTON                    1105
#define IDC_MODEL2D_RADIO               1106
#define IDC_DOWNBUTTON                  1106
#define IDC_MODEL3D_RADIO               1107
#define IDC_DELETEBUTTON                1107
#define IDC_CELLHEADER_RADIO            1108
#define IDC_SHAREDCELL_RADIO            1109
#define IDC_FILENAME_EDIT               1110
#define IDC_PATHLIST                    1111
#define IDC_LIST1                       1112
#define IDC_MARGINTOP_EDIT              1113
#define IDC_MARGINBOTTOM_EDIT           1114
#define IDC_MARGINELEFT_EDIT            1115
#define IDC_MARGINLEFT_EDIT             1115
#define IDC_MARGINRIGHT_EDIT            1116
#define IDC_EX_MONO_CHECK               1117
#define IDC_PLOTSTYLETABLE              1118
#define IDC_EDIT_PLOTSTYLETABLE         1119
#define IDC_BROWSE2                     1120
#define IDC_EDIT_COLOR_IMAGES_DPI       1121
#define IDC_EDIT_BW_IMAGES_DPI          1122
#define IDC_TRANSPARENCY                1123
#define IDC_BUTTON_CUSTOM_PROPERTIES    1124
#define IDC_TEXT_SEARCHABLE             1125
#define IDC_PDFEXPORT_COLOR_POLICY      1126
#define IDC_EMEDDED_OPTIMIZED           1127
#define IDC_PRC                         1128
#define IDC_PRC2                        1129
#define IDC_ENCODED2                    1130
#define IDC_PDFEXPORT_HATCHEXPTYPE      1131
#define IDC_PDFEXPORT_OTHERHATCHEXPTYPE 1132
#define IDC_HYPERLINK                   1133
#define IDC_EDIT_HATCH_DPI              1134
#define IDC_EDIT_GEOM_DPI               1135
#define IDC_CROP                        1136
#define IDC_EDIT_GEOM_DPI2              1136
#define IDC_EDIT_DATABASE_LSSCALE       1136
#define IDC_DCT                         1137
#define IDC_SLIDER_QUALITY              1138
#define IDC_STATIC_IQ                   1139
#define IDC_MFCCOLORBUTTON1             1140
#define IDC_CUSTOM1                     1141
#define IDC_COLOR_BUTTON_CUSTOM         1141
#define ID_COLOR_BTN                    1142
#define ID_COLOR_BTN0                   1142
#define IDC_BUTTON_DELETE_LINK          1146
#define IDC_BUTTON4                     1147
#define IDC_BUTTON5                     1148
#define IDC_BUTTON7                     1150
#define IDC_BUTTON8                     1151
#define IDC_LIST_ATTRS                  1152
#define IDC_CHECK2                      1152
#define IDC_EMPTYTEXTS_CHECK            1152
#define IDC_CHECK1                      1153
#define IDC_LINEARIZED                  1154
#define IDC_BG_CHECK                    1154
#define IDC_CELLDEF_CHECK               1154
#define IDC_COMBO_MERGE_CONTROL         1155
#define IDC_DISPLAYBOUNDARY_CHECK       1155
#define IDC_LS_CHECK                    1155
#define IDC_CAMERA_CHECK                1156
#define IDC_LEVELS_CHECK                1156
#define IDC_CLIPBACK_CHECK              1157
#define IDC_DS_CHECK                    1157
#define IDC_CLIPFRONT_CHECK             1158
#define IDC_MLS_CHECK                   1158
#define IDC_CLIPVOLUME_CHECK            1159
#define IDC_TEMP_CHECK                  1159
#define IDC_CONSTRUCTIONS_CHECK         1160
#define IDC_DEF_LIGHTING_CHECK          1161
#define IDC_FAST_CURVES_CHECK           1161
#define IDC_DIM_CHECK                   1162
#define IDC_FIELDS_CHECK                1163
#define IDC_DISPLAYSET_CHECK            1164
#define IDC_FASTCELLS_CHECK             1165
#define IDC_FILLS_CHECK                 1166
#define IDC_GRID_CHECK                  1167
#define IDC_LEVELOVERRIDE_CHECK         1168
#define IDC_LSTYLE_CHECK                1169
#define IDC_LWEIGHT_CHECK               1170
#define IDC_TEXTURE_CHECK               1171
#define IDC_PATTERNS_CHECK              1172
#define IDC_TAGS_CHECK                  1173
#define IDC_TEXT_CHECK                  1174
#define IDC_TEXTNODE_CHECK              1175
#define IDC_TRANSPARENCY_CHECK          1176
#define IDC_DISPLAYSTYLE_COMBO          1177
#define IDC_ACS_CHECK                   1178
#define IDC_EDITFIELD                   1179
#define IDC_FIELD_NAME                  1188
#define IDC_BUTTON_SET_ACTIVE           1191
#define IDC_BUTTON_NEW                  1192
#define IDC_LIST_COLORS                 1193
#define IDC_LIST_LINESTYLE              1195
#define IDC_COMBO_PDF_A                 1196
#define IDC_MEASURING                   1197
#define IDC_SPACETEXTS_CHECK            1198
#define IDC_USE_GS_CACHE                1198
#define IDC_TS_CHECK                    1199
#define IDC_XREFLEVELS_CHECK            1200
#define IDC_ITEMLIBS_CHECK              1201
#define IDC_EMPTYCELL_CHECK             1202
#define IDC_ITEMLIBS_CHECK2             1203
#define IDC_XREFNOTLOADED_CHECK         1203
#define IDC_ITEM_LIB_COMBO              1206
#define IDC_LIB_NAME_EDIT               1207
#define IDC_ITEM_TYPE_LIST              1208
#define IDC_ADD_ITEM_TYPE_BUTTON        1209
#define IDC_ADD_PROP_TYPE_BUTTON        1210
#define IDC_DEL_ITEM_TYPE_BUTTON        1211
#define IDC_ITEM_TYPE_NAME_EDIT         1212
#define IDC_PROP_TYPE_NAME_EDIT         1213
#define IDC_PROPERTY_LIST               1214
#define IDC_PROP_NAME_EDIT              1215
#define IDC_PROP_TYPE_COMBO             1217
#define IDC_ARRAY_CHECK                 1218
#define IDC_ITEM_TYPE_COMBO             1220
#define IDC_ADD_PROP_BUTTON             1221
#define IDC_LIB_COMBO                   1221
#define IDC_EDIT_PROP_BUTTON            1222
#define IDC_PROPERTIES_LIST             1222
#define IDC_DEL_PROP_BUTTON             1223
#define IDC_VALUE_STATIC                1223
#define IDC_ARRAY_STATIC                1224
#define IDC_ARRAY_LIST                  1225
#define IDC_ARR_VALUE_EDIT              1226
#define IDC_ARR_ADD_BUTTON              1227
#define IDC_ARR_DEL_BUTTON              1228
#define IDC_ARR_EDIT_BUTTON             1229
#define IDC_GRADCOLOR_RED               1298
#define IDC_GRADCOLOR_GREEN             1299
#define IDC_GRADCOLOR_SELECTED          1300
#define IDC_GRADCOLOR_BLUE              1301
#define IDC_GRADCOLOR_CHOOSE            1302
#define IDC_BHIGHLIGHT                  1312
#define IDC_SPREVIEW                    1323
#define IDC_SPOSITION                   1328
#define IDC_STARGET                     1329
#define IDC_CBON                        1330
#define IDC_CBTARGETED                  1331
#define IDC_EINTENSITY                  1332
#define IDC_SCOLOR                      1333
#define IDC_BCOLOR                      1334
#define IDC_LBMATERIALS                 1335
#define IDC_EHOTSPOT                    1335
#define IDC_CBDIAGBKGND                 1336
#define IDC_EFALLOFF                    1336
#define IDC_SAMBIENT                    1337
#define IDC_BAMBIENT                    1338
#define IDC_SDIFFUSE                    1339
#define IDC_BDIFFUSE                    1340
#define IDC_SSPECULAR                   1341
#define IDC_BSPECULAR                   1342
#define IDC_SDIFFUSEMAP                 1343
#define IDC_SGLOSS                      1344
#define IDC_SOPACITY                    1345
#define IDC_SSELFILLUMINATION           1346
#define IDC_SNAME                       1347
#define IDC_SDESCRIPTION                1348
#define IDC_SBRIGHTNESS_COLOR           1348
#define IDC_CBDEVICE                    1349
#define IDC_PDF_FILENAME                1350
#define IDC_LIST_PDF_PAGES              1351
#define IDC_PDF_PREVIEW                 1352
#define IDC_LIST_LAYERS                 1353
#define IDC_LIST_VIEWS                  1354
#define IDC_COMBO_LINE_SCALE_TYPE       1355
#define IDC_EDIT_MODEL_GLOBAL_LSSCALE   1356
#define IDC_EDIT_MODEL_ANNOTATION_SCALE 1357
#define IDC_COMBO_XREFNAME              1358
#define IDC_BINDTOCELL                  1359
#define IDC_CLIPSUPPORT                 1360
#define IDC_CLIPSUPPORT2                1361
#define IDC_COLORTABLESUPPORT           1361
#define ID_SAVE_COLORS                  1362
#define ID_LOAD_COLORS                  1363
#define IDC_PROP_LIST                   1364
#define IDC_X1_EDIT                     1366
#define IDC_COL1_STATIC                 1367
#define IDC_X1_STATIC                   1368
#define IDC_ADD                         1368
#define IDC_Y1_EDIT                     1369
#define IDC_MODIFY                      1369
#define IDC_STRANS                      1369
#define IDC_Y1_STATIC                   1370
#define IDC_TRANS_VAL                   1370
#define IDC_Z1_EDIT                     1371
#define IDC_Z1_STATIC                   1372
#define IDC_BOOL_STATIC                 1372
#define IDC_TRUERADIO                   1373
#define IDC_FALSERADIO                  1374
#define IDC_VALUEEDIT                   1375
#define IDC_XEDIT                       1376
#define IDC_COL2_STATIC                 1380
#define IDC_ARRAYVALUES_LIST            1380
#define IDC_X2_STATIC                   1381
#define IDC_X2_EDIT                     1382
#define IDC_Y2_STATIC                   1383
#define IDC_Y2_EDIT                     1384
#define IDC_Z2_STATIC                   1385
#define IDC_PROPTYPE_COMBO              1385
#define IDC_Z2_EDIT                     1386
#define IDC_X3_STATIC                   1387
#define IDC_X3_EDIT                     1388
#define IDC_Y3_STATIC                   1389
#define IDC_Y3_EDIT                     1390
#define IDC_Z3_STATIC                   1391
#define IDC_Z3_EDIT                     1392
#define IDC_W_STATIC                    1393
#define IDC_W_EDIT                      1394
#define ID_VECTORIZE                    32771
#define ID_VIEW_ZOOM_WINDOW             32773
#define ID_VIEW_ZOOMIN                  32774
#define ID_VIEW_ZOOMOUT                 32775
#define ID_VIEW_ZOOMEXTENTS             32776
#define ID_VIEW_PAN                     32777
#define ID_VIEW_3DORBIT                 32778
#define ID_VIEWER_REGEN                 32779
#define ID_VIEWER_VPREGEN               32780
#define ID_2DWIREFRAME                  32781
#define ID_3DWIREFRAME                  32782
#define ID_HIDDEN                       32783
#define ID_FLAT_SHADED                  32784
#define ID_GOURAUD_SHADED               32785
#define ID_FLAT_SHADED_WITH_EDGES       32786
#define ID_GOURAUD_SHADED_EDGES_ON      32787
#define ID_TOOLS_LOADAPPLICATIONS       32788
#define ID_TOOLS_SOLIDHELPER            32789
#define ID_TOOLS_SETREGVARS             32791
#define ID_FILE_PARTIAL_OPEN            32792
#define ID_FILE_RECOVER                 32793
#define ID_VIEW_CLASSESINFO             32794
#define ID_SETREGVARS_MS_SYMBRSRC       32795
#define ID_VIEW_SYSTEMVARIABLES         32796
#define ID_SETREGVARS_MS_RSRC           32797
#define ID_VIEW_SUMMINFO                32798
#define ID_EDIT_RECENTCOMMAND           32799
#define ID_VIEW_FILEDEPENDENCY          32800
#define ID_SETREGVARS_FAST              32801
#define ID_VIEW_SETACTIVELAYOUT         32802
#define ID_SETREGVARS_FAST_FONT         32803
#define ID_VIEW_NAMEDVIEWS              32804
#define ID_REFRESH                      32805
#define ID_VECTORIZE_ADDVECTORIZERDLL   32806
#define ID_VECTORIZE_CLEARMENU          32807
#define ID_VECTORIZER_FIRST             32808
#define ID_FILE_BMPEXPORT               32817
#define ID_VECTORIZER_LAST              32818
#define ID_FILE_EXPORT_SVG              32819
#define ID_FILE_EXPORTTOHOOPS           32820
#define ID_FILE_EXPORT_HOOPS            32821
#define ID_FILE_EXPORTTOPDF             32822
#define ID_FILE_EXPORT_PDF              32823
#define ID_SWITCH_MODEL                 32824
#define ID_TOOLS_MODELEROPTIONS         32825
#define ID_Menu                         32826
#define ID_FILE_STL                     32827
#define ID_SETREGVARS_MS_PATTERN        32828
#define ID_SETREGVARS_MS_BUMP           32829
#define ID_TOOLS_OPTIONS                32830
#define ID_OPTIONS_USEGSMODEL           32831
#define ID_OPTIONS_USEGSMODELGEOMETRYCACHE 32832
#define ID_SETREGVARS_MS_MATERIAL       32833
#define ID_SETREGVARS_MS_MTBL           32834
#define ID_SETREGVARS_MS_MATPALETTE     32835
#define ID_TOOLS_TESTS                  32836
#define ID_TESTS_VIEWCAMERA             32837
#define ID_SETREGVARS_MS                32838
#define ID_SETREGVARS_NURBS             32839
#define ID_EDIT_CLEARSELECTION          32840
#define ID_EDIT_SELECTIONREACTOR        32841
#define ID_FILE_EXPORTTODWF             32842
#define ID_FILE_EXPORT_TODWF            32843
#define ID_FILE_EXPORT_DWF              32844
#define ID_SETREGVARS_GRIP              32845
#define ID_FILE_CLIPWITH                32846
#define ID_FILE_PAGESETUP               32846
#define ID_CLIPWITH_MASK                32847
#define ID_FILE_PAGE_SETUP_MANAGER      32847
#define ID_FILE_PRINTPREVIEW            32848
#define ID_OPTIONS_DISABLEASSERTS       32849
#define ID_TESTS_CELLLIBRARYPREVIEW     32850
#define ID_SETREGVARS_MS32851           32851
#define ID_SETREGVARS_MSPANTABLE        32852
#define ID_SETREGVARS_MS_PENTABLE       32853
#define ID_OPTIONS_3DOBJ_WF_ISOLINES    32854
#define ID_SETREGVARS_MS32855           32855
#define ID_SETREGVARS_MS_DEFCTBL        32856
#define ID_OPTIONS_USE_XREFCLRTBL       32857
#define ID_OPTIONS_REMAP_CLRIDX         32858
#define ID_TESTS_LOADSMARTSOLID         32859
#define ID_TESTS_OPTIONS                32860
#define IDC_BUTTON_LINKS_ATTR_DLG       32860
#define ID_TOOLS_BGCOLOR                32861
#define ID_Menu32861                    32861
#define IDD_BGCOLOR_DIALOG              32862
#define ID_EDIT_SWITCHVIEWGROUP         32862
#define IDC_SELECT_BGCOLOR              32863
#define ID_OPTIONS_USESINGLEVIEWMODE    32863
#define IDC_CANCEL_BGCOLOR              32864
#define ID_VIEW_3DVIEWS                 32864
#define IDC_LISTBOX_BGCOLOR             32865
#define IDC_LISTCTRL_BGCOLOR            32866
#define ID_LAYER_PROPERTIES_MANAGER     32873
#define IDC_BUTTON_ADD                  32874
#define ID_FORMAT_LAYER                 32875
#define IDD_LAYER_PROPERTIES_MANAGER    32876
#define IDD_LEVEL_PROP_MANAGER          32876
#define IDD_LAYER_PROPERTIES_LINEWEIGHT 32877
#define IDD_LEVEL_PROPERTIES_LINEWEIGHT 32877
#define IDD_LAYER_PROPERTIES_COLOR      32878
#define IDD_LAYER_PROPERTIES_LINETYPE   32879
#define IDB_LAYER_FILTERS               32880
#define IDD_LAYER_PROPERTIES_FILTER     32881
#define IDR_LAYER_POPUP_MENU            32883
#define IDR_LEVEL_POPUP_MENU            32883
#define IDC_STATIC_CURRENT_LEVEL        32884
#define IDC_STATIC_ACTIVE_LEVEL         32884
#define IDC_STATIC_LEVEL_STATISTIC      32885
#define IDC_LIST_LAYERS_LIST            32886
#define IDC_LIST_LEVELS                 32886
#define IDC_UPDATE_LAYERS_BUTTON        32887
#define IDC_LAYER_FILTER_TREE           32888
#define IDC_LEVEL_FILTER_TREE           32888
#define IDC_LAYERS                      32889
#define IDC_LAYERS2                     32890
#define IDC_OFFLAYERS                   32891
#define IDC_LIST_LAYER                  32892
#define ID_PURGE_LAYERS                 32893
#define ID_VP_OVR_CLEAR_ALL_FOR_CURR_VP 32894
#define ID_VP_OVR_REMOVE_COLOR          32895
#define ID_VP_OVR_REMOVE_LINETYPE       32896
#define ID_VP_OVR_REMOVE_LINEWEIGHT     32897
#define ID_VP_OVR_REMOVE_PLOTSTYLE      32898
#define ID_VP_OVR_CLEAR_ALL_FOR_ALL_VP  32899
#define ID_VP_OVR_REMOVE_TRANSPARENCY   32900
#define IDC_LIST_LINEWEIGHT             32901
#define IDC_STATIC_LINEWEIGHT_ORIGINAL  32902
#define ID_VIEW1                        32903
#define ID_VIEW2                        32904
#define ID_VIEW3                        32905
#define ID_VIEW4                        32906
#define ID_VIEW5                        32907
#define ID_VIEW6                        32908
#define ID_VIEW7                        32909
#define ID_VIEW8                        32910
#define ID_VIEWS                        32911
#define IDC_BUTTON_SET_CURRENT          32912
#define ID_3DVIEWS_TOP                  32913
#define ID_3DVIEWS_BOTTOM               32914
#define ID_3DVIEWS_LEFT                 32915
#define ID_3DVIEWS_RIGHT                32916
#define ID_3DVIEWS_FRONT                32917
#define ID_3DVIEWS_BACK                 32918
#define ID_3DVIEWS_SW                   32919
#define ID_3DVIEWS_SE                   32920
#define ID_3DVIEWS_NE                   32921
#define ID_3DVIEWS_NW                   32922
#define ID_OPTIONS_ACTIVELEVELALWAYSVISIBLE 32923
#define ID_VIEW_RENDER                  32924
#define ID_RENDER_LIGHTS                32925
#define ID_RENDER_MATERIALS             32926
#define ID_OPTIONS_PROCESSTAGASSOCIATION 32927
#define ID__PRESENTATION                32928
#define ID__VIEWFLAGS                   32929
#define ID_VIEWFLAGS                    32930
#define ID_XY_PLANE                     32931
#define ID_BOTTOM                       32932
#define ID_YZ_PLANE                     32933
#define ID_RIGHT                        32934
#define ID_XZ_PLANE                     32935
#define ID_BACK                         32936
#define ID_SW_ISOMETRIC                 32937
#define ID_SE_ISOMETRIC                 32938
#define ID_NE_ISOMETRIC                 32939
#define ID_NW_ISOMETRIC                 32940
#define IDC_BUTTON_PROPERTIES           32944
#define ID_FORMAT_LEVELMANAGER          32945
#define ID_TOOLS_LEVELMANAGER           32946
#define ID_TOOLS_LEVEL                  32947
#define ID_FILE_COMPRESS                32948
#define ID_CREATEFENCE_BTN              32949
#define ID_ITEM_TYPE_LIB_BUTTON         32950
#define ID__ITEMTYPES                   32951
#define ID_ITEMTYPES                    32952
#define ID_CREATEFENCE_CIRCLE           32953
#define ID_OPTIONS_USEGSBLOCKGEOMETRYCACHE 32954
#define ID_FILE_OBJ                     32955
#define ID_TESTS_LOADLINESTYLES         32956
#define ID_OPTIONS_EXACTEXTENTS         32957
#define ID_OPTIONS_MTLOADING            32958
#define ID_INSERT_RASTER_ATTACH         32959
#define ID_SETREGVARS_MS_FONTPATH       32960
#define ID_OPTIONS_MTREGEN              32961
#define ID_OPTIONS_LSSCALE              32962
#define ID_TESTS_MERGE_MODELS           32963
#define ID_TESTS_MERGE_XREF             32964
#define ID_OPTIONS_PROCESSDIMASSOCIATION 32965
#define ID_OPTIONS_PROCESSMLINEASSOCIATION 32966
#define ID_OPTIONS_APPLYGLOBALORIGIN    32967
#define ID_OPTIONS_TRANSFORMLSSCALE     32968
#define IDD_PDF_SECURITY_DIALOG         32969
#define IDC_EDIT_USER_PASSWORD          32970
#define IDC_EDIT_OWNER_PASSWORD         32971
#define IDC_PDF_SC_ALLOW_EXTRACT        32972
#define IDC_PDF_SC_ALLOW_ASSEMBLE       32973
#define IDC_PDF_SC_ALLOW_ANNOTATE       32974
#define IDC_PDF_SC_ALLOW_FORM_FILL      32975
#define IDC_PDF_SC_ALLOW_MODIFY         32976
#define IDC_PDF_SC_ALLOW_PRINT_ALL      32977
#define IDC_PDF_SC_ALLOW_PRINT_LOW      32978
#define IDC_BUTTON_PDF_SECURITY         32979
#define ID__PROPERTIES                  32969
#define ID_CDA_PROPERTIES               32970

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         32980
#define _APS_NEXT_CONTROL_VALUE         1386
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
