/////////////////////////////////////////////////////////////////////////////// 
// Copyright (C) 2002-2022, Open Design Alliance (the "Alliance"). 
// All rights reserved. 
// 
// This software and its documentation and related materials are owned by 
// the Alliance. The software may only be incorporated into application 
// programs owned by members of the Alliance, subject to a signed 
// Membership Agreement and Supplemental Software License Agreement with the
// Alliance. The structure and organization of this software are the valuable  
// trade secrets of the Alliance and its suppliers. The software is also 
// protected by copyright law and international treaty provisions. Application  
// programs incorporating this software must include the following statement 
// with their copyright notices:
//   
//   This application incorporates Open Design Alliance software pursuant to a license 
//   agreement with Open Design Alliance.
//   Open Design Alliance Copyright (C) 2002-2022 by Open Design Alliance. 
//   All rights reserved.
//
// By use of this software, its documentation or related materials, you 
// acknowledge and accept the above terms.
///////////////////////////////////////////////////////////////////////////////
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OdaMfcApp.rc
//
#define ID_VIEW_ZOOMIN                  1
#define ID_TREE_VIEW                    1
#define IDOK2                           2
#define IDCOPY                          3
#define IDURL                           4
#define IDPREVIEW                       5
#define IDD_ABOUTBOX                    100
#define IDD_ODAMFCAPP_FORM              101
#define IDS_APPLICATION_DESC            102
#define IDS_DOCUMENTS_DESC              103
#define IDD_DIALOGBAR                   103
#define IDD_DIALOGBAR_TEXT_EDIT         103
#define IDS_DOCUMENT_DESC               104
#define IDS_ERROR_NOITEM                105
#define IDS_ERROR_NOACTIVEDOC           106
#define IDS_ERROR_OPENFAILED            107
#define IDR_ODAFILEFIXER                127
#define IDR_MAINFRAME                   128
#define IDR_ODAMFCTYPE                  129
#define IDD_CLASSES                     131
#define IDD_PROPERTIES                  133
#define IDD_SUMMINFO                    142
#define IDD_FIND_DLG                    143
#define IDD_AUDITINFO                   147
#define IDD_CREATEDRAWING               148
#define IDD_SetActiveLayoutDlg          149
#define IDD_DIALOG_LOAD_LINETYPE        150
#define IDD_XREFVIEW                    151
#define IDR_VIEWER                      151
#define IDD_LOAD_APPS                   152
#define IDD_RENDER_MATERIALS            153
#define IDD_RENDER_LIGHTS               154
#define IDD_TRIANGULATIONPARAMS         155
#define IDD_LAYER_PROPERTIES_MANAGER    156
#define IDD_LAYER_PROPERTIES_LINEWEIGHT 158
#define IDD_LAYER_PROPERTIES_COLOR      159
#define IDD_LAYER_PROPERTIES_LINETYPE   160
#define IDD_PASSWORD_DLG                161
#define IDD_FILE_PUBLISH                162
#define IDD_PUBLISH_SHEETS              163
#define IDD_PUBLISH_SETTING             164
#define IDD_LINEWEIGHT_SETTINGS         165
#define IDD_DIALOG_NAMED_VIEWS          166
#define IDD_FILEDEPENDENCY              168
#define IDR_XREFMAN_BAR                 169
#define IDB_XREFBAR                     174
#define IDD_CONSOLE_DLG                 177
#define IDD_ACIS_SAVE_TO                178
#define IDD_STATIC_APPS                 179
#define IDB_LAYER_FILTERS               182
#define IDD_LAYER_PROPERTIES_FILTER     183
#define IDD_PAGE_SETUP                  184
#define IDD_SNAP_DIALOG                 185
#define IDD_DIALOG_NEW_VIEW             186
#define IDD_MLSTYLE                     187
#define IDD_PDFEXPORT                   188
#define IDD_PS_DLG_GENEGAL              189
#define IDD_PS_DLG                      190
#define IDD_PS_DLG_FORMVIEW             191
#define IDB_SELECT_TRUE_COLOR           200
#define IDD_PS_DLG_ADDPS                201
#define IDB_PS_BITMAP_GENERAL_CTB       202
#define IDB_PS_BITMAP_GENERAL_STB       203
#define IDD_PS_DLG_LINEWEIGHT           204
#define IDB_LAYER_STATES                205
#define IDB_PS_BITMAP_CHECK             206
#define IDB_PS_BITMAP_WHITE             207
#define IDD_PAGE_SETUP2                 208
#define IDD_PAGESETUP                   209
#define IDD_PRINTERPLOTTER              210
#define IDD_PAGESIZE                    211
#define IDD_PLOTOPTION                  212
#define IDD_PLOTAREA                    213
#define IDD_PLOTOFFSET                  214
#define IDD_PLOTSCALE                   215
#define IDD_DRAWINGORIENTATION          216
#define IDC_PAGESETUP_NAME              217
#define IDC_PAGESETUP_PLOTTER           218
#define IDC_PAGESETUP_WHERE             219
#define IDC_PAGESETUP_DESCRIPTION       220
#define IDD_PLOTSTYLETABLE              221
#define IDD_SHADEDVIEWPORTOPTIONS       222
#define IDD_PLOTOFFSET2                 223
#define IDD_PLOTOFFSET3                 224
#define IDR_LAYER_POPUP_MENU            225
#define IDD_DwfUnderlay                 226
#define IDD_BACKGROUND_COLOR            227
#define IDD_REMOTE_GEOMETRY_PROPS       228
#define IDD_RGV_PREVIEW                 229
#define IDD_PDFEXPORT_PREVIEW           230
#define IDD_RENDER_SNAPSHOT             231
#define IDD_ABOUTBOX1                   232
#define IDD_RENDER_DBLIGHTS             232
#define IDD_PDFNOTIFICATION             233
#define IDD_RENDER_DBMATERIALS          234
#define IDD_RENDER_VECTPROPS            235
#define IDD_SIMPLE_INPUT                236
#define IDD_EXTEXT_DLG                  237
#define IDB_TEIGHA_BASE_BMP             239
#define IDD_CUSTOM_MEDIA                241
#define IDD_DIALOG_CUSTOM_PROPERTIES    242
#define IDD_RENDER_DBVISUALSTYLES       244
#define IDD_RENDER_ODCMENTITYCOLOR      245
#define IDD_BRANCHES                    246
#define IDD_UNDO_LIST                   247
#define IDD_VS_FLAGSEDITOR              248
#define IDD_RENDER_ENVIRONMENT          249
#define IDD_DIALOG_REVISIONS            250
#define IDD_COMMIT_DIALOG               251
#define IDD_DIALOG_MERGE                252
#define IDD_DIALOG_BBERRORS             253
#define IDD_TABPAGE_DIALOG              257
#define IDD_TEXTURE_DIALOG              260
#define IDD_MECH_BOM_PROPERTIES         261
#define IDD_MECH_BOM_SETTINGS           262
#define IDD_MECH_STRUCTURE              263
#define IDR_MECH_COMPTREE_MENU          264
#define IDR_MECHSYMBAR                  265
#define IDD_MECH_STANDARDS_MANAGER      266
#define IDD_MECH_BOMMANAGER             267
#define IDD_MECH_STDMGR_UPDMEASURE      268
#define IDD_MECH_STDMGR_ISREFERENCED    269
#define IDD_MECH_STDMGR_RENAME          270
#define IDD_MECH_STDMGR_RESETDEFAULTS   271
#define IDD_MECH_STDMGR_UPDMEASUREMENT  272
#define IDD_MECH_STDMGR_RESTOREDEFAULTS 273
#define IDD_MECH_STDMGR_NEWSTD          274
#define IDD_MECH_STDMGR_SETTINGS        275
#define IDR_MECH_STDMGR_LISTMENU        276
#define IDR_MECH_STDMGR_TREEMENU        277
#define IDR_MECH_SYMBOLS                278
#define IDD_DIALOG_LAYER_STATES         281
#define IDD_DIALOG_NEW_LAYER_STATE      283
#define IDD_MERGE_VIEWBMP               284
#define IDC_OWNERSHIPTREE               1000
#define IDC_OBJECTDATA                  1003
#define IDC_TREE1                       1006
#define IDC_PROPLIST                    1013
#define IDC_SUMMINFO_LIST               1015
#define IDC_VALUE                       1016
#define IDC_BUTTON1                     1017
#define IDC_EDIT1                       1018
#define IDC_DELETE_ALL_BLOCKS           1018
#define IDC_BUTTON3                     1018
#define IDC_PS_FORMVIEW_EDIT_VIRTPEN    1019
#define IDC_SHOW_ALL_BLOCKS             1019
#define IDC_EDIT_TR01                   1019
#define IDC_BUTTON4                     1019
#define IDC_AUDITINFO_LIST              1020
#define IDC_EDIT_TR02                   1020
#define IDC_AUDITSUM_LIST               1021
#define IDC_EDIT_TR03                   1021
#define IDC_BUTTON6                     1021
#define IDC_ST_AUDITSUM                 1022
#define IDC_EDIT_TR10                   1022
#define IDC_BUTTON7                     1022
#define IDC_ST_AUDITERR                 1023
#define IDC_EDIT_TR11                   1023
#define IDC_EDIT_TR12                   1024
#define IDC_EDIT_TR13                   1025
#define IDC_RADIO_ENGL                  1026
#define IDC_EDIT_TR20                   1026
#define IDC_RADIO_METRIC                1027
#define IDC_EDIT_TR21                   1027
#define IDC_LAYOUTLIST                  1028
#define IDC_EDIT_TR22                   1028
#define IDC_EDIT_TR23                   1029
#define ID_OPEN_LINETYPEFILE            1030
#define IDC_EDIT_TR30                   1030
#define ID_LOAD_SELECTION               1031
#define IDC_EDIT_TR31                   1031
#define IDC_BUTTON_LOAD_ALL             1032
#define IDC_EDIT_TR32                   1032
#define IDC_EDIT_TR33                   1033
#define IDC_LIST_LINETYPE               1035
#define IDC_XREFTREE                    1036
#define IDC_INF_LIBRARY                 1038
#define IDC_ALAYOUT_CLOSE               1039
#define IDC_UNLOAD_APP                  1040
#define IDC_LOAD_APP                    1041
#define IDC_APPS_LIST                   1042
#define IDC_MATERIALS_LIST              1043
#define IDC_LIGHTS_LIST                 1044
#define IDC_TP_MAXFACETEDGELENGTH       1045
#define IDC_TP_NORMTOL                  1046
#define IDC_TP_NORMALTOL                1046
#define IDC_TP_SURFTOL                  1047
#define IDC_TP_SURFACETOL               1047
#define IDC_TP_GRIDASPECTRATIO          1048
#define IDC_TP_MAXNUMGRIDLINES          1049
#define IDC_STATIC_CURRENT_LAYER        1050
#define IDC_TP_POINTS_PER_EDGE          1050
#define IDC_TP_POINTSPEREDGE            1050
#define IDC_STATIC_LAYER_STATISTIC      1051
#define IDC_LIST_LAYERS_LIST            1052
#define IDC_FACETRES                    1052
#define IDC_BUTTON_SET_CURRENT          1053
#define IDC_BUTTON_ADD                  1054
#define IDC_LIST_LINEWEIGHT             1057
#define IDC_STATIC_LINEWEIGHT_ORIGINAL  1058
#define IDC_LIST_COLORS                 1060
#define IDC_BUTTON_LOAD_LINETYPE        1061
#define IDC_NEWNAME                     1062
#define IDC_RENAME                      1063
#define IDC_TP_NURBSURFACE              1064
#define IDC_EDIT_PWD                    1064
#define IDC_TP_BETWEENKNOTS             1064
#define IDC_PUBLISH_SETTINGS            1065
#define IDC_PUBLISH_FILE_NAME_EDIT      1069
#define IDC_PUBLISH_BROWSE_BUTTON       1070
#define IDC_PUBLISH_BINARY_RADIO        1071
#define IDC_PUBLISH_ASCII_RADIO         1072
#define IDC_PUBLISH_REMOVE_BUTTON       1073
#define IDC_PUBLISH_PASSWORD_EDIT       1075
#define IDC_PUBLIS_SETTING_BUTTON       1076
#define IDC_PUBLISH_LAYOUTS_LIST        1077
#define IDC_PUBLISH_SET_LAYOUT          1078
#define IDC_PUBLISH_SET_SHEET           1079
#define IDC_PUBLISH_SET_DRAWING         1080
#define IDC_PUBLISH_SET_AUTHOR          1081
#define IDC_PUBLISH_SET_SUBJECT         1082
#define IDC_PUBLISH_SET_COMPANY         1083
#define IDC_PUBLISH_SET_COMMENTS        1084
#define IDC_PUBLISH_SET_PREVIEW_FILE    1085
#define IDC_PUBLISH_SET_BROWSE_PREVIEW  1086
#define IDC_PUBLISH_SET_WIDTH           1087
#define IDC_PUBLISH_SET_HEIGHT          1088
#define IDC_PUBLISH_SET_COLOR_DEPTH     1089
#define IDC_RADIO_MM                    1090
#define IDC_RADIO_IN                    1091
#define IDC_DISPLAY_LINEWEIGHT          1092
#define IDC_SLIDER_SCALE                1093
#define IDC_COMBO_DEFAULT               1095
#define IDC_LINEWEIGHTS                 1096
#define IDC_STATIC_CURLW                1097
#define IDC_NAMEDVIEWS                  1098
#define IDC_SETCURRENT_BUTTON           1099
#define IDC_FILEDEP_LIST                1100
#define IDC_NEW_BUTTON                  1100
#define IDC_PASS_FILE_NAME              1101
#define IDC_UPDATE_LAYERS_BUTTON        1101
#define IDC_ATTACH                      1102
#define IDC_DELETE_BUTTON               1102
#define IDC_DETACH                      1103
#define IDC_RELOAD                      1104
#define IDC_UNLOAD                      1105
#define IDC_BIND                        1106
#define IDC_XREFLIST                    1108
#define IDC_FOUND_PATH                  1109
#define IDC_SAVEPATH                    1110
#define IDC_BROWSE                      1111
#define IDC_INPUT                       1115
#define IDC_PROMPT                      1116
#define IDC_ACIS_VER                    1117
#define IDSAVE                          1120
#define IDC_EDIT_ACIS                   1121
#define IDLOADFROM                      1122
#define IDC_BASE_ACIS_VER               1123
#define IDC_CHECK_INDEXES               1124
#define IDC_CHECK_STANDARD_SAVE         1125
#define IDSETTOENTITY                   1126
#define IDC_APPLIST                     1127
#define IDCREATENEW                     1127
#define IDC_LAYER_FILTER_TREE           1128
#define IDCREATENEWALL                  1128
#define IDC_EDIT_LF_DEFINITION          1129
#define IDSAVE2                         1129
#define IDSAVESAB                       1129
#define IDC_EDIT_LF_NAME                1130
#define IDLOADFROM2                     1130
#define IDBBCHECK                       1130
#define IDSAVE3                         1131
#define IDACISCHECK                     1131
#define IDC_PAGESETUP_AREA              1132
#define IDC_PAGESETUP_UNIT_IN           1133
#define IDC_PAGESETUP_UNIT_MM           1134
#define IDC_PAGESETUP_SIZE              1135
#define IDC_PAGESETUP_SCALE             1136
#define IDC_PAGESETUP_OFFSET_X          1137
#define IDC_PAGESETUP_OFFSET_Y          1138
#define IDC_PAGESETUP_PAPER_UNIT        1139
#define IDC_PAGESETUP_DRAWING_UNIT      1140
#define IDC_PAGESETUP_PORTRAIT          1141
#define IDC_PAGESETUP_LANDSCAPE         1142
#define IDC_PAGESETUP_DEVICE            1143
#define IDC_PAGESETUP_PAPER_UNIT_STATIC 1144
#define IDC_PAGESETUP_DRAWING_UNIT_STATIC 1145
#define IDC_PAGESETUP_OFFSET_X_STATIC   1146
#define IDC_PAGESETUP_OFFSET_Y_STATIC   1147
#define IDC_STATIC_EQ                   1148
#define IDC_PAGESETUP_PLOTAREATYPE      1148
#define IDC_STATIC_AREA                 1149
#define IDC_PAGESETUP_VIEWS             1149
#define IDC_BODY_LIST                   1150
#define IDC_PAGESETUP_SHADE_PLOT        1150
#define IDC_CHECK1                      1151
#define IDC_CHECK2                      1152
#define IDC_PAGESETUP_DPI               1152
#define IDC_CHECK3                      1153
#define IDC_CHECK4                      1154
#define IDC_CHECK5                      1155
#define IDC_CHECK6                      1156
#define IDC_CHECK7                      1157
#define IDC_CHECK8                      1158
#define IDC_CHECK9                      1159
#define IDC_CHECK10                     1160
#define IDC_COMBO_VIEWCATEGORY          1161
#define IDC_CHECK_STORE_LS              1162
#define IDC_CHECK_SAVEUCS               1163
#define IDC_EDIT_VIEWNAME               1164
#define IDC_COMBO_MLSTYLE_CURRENT       1165
#define IDC_COMBO_UCSNAME               1166
#define IDC_EDIT_MLSTYLE_NAME           1166
#define IDC_EDIT_MLSTYLE_DESCR          1167
#define IDC_BUTTON_MLSTYLE_SAVE         1168
#define IDC_BUTTON_MLSTYLE_LOAD         1169
#define IDC_BUTTON_SAVE_LINETYPE        1170
#define IDC_INF_COPYRIGHT               1171
#define IDC_EDIT_FILE                   1172
#define IDC_CANCEL                      1173
#define IDC_EMEDDED                     1177
#define IDC_TTF_AS_GEOM                 1178
#define IDC_SHX_AS_GEOM                 1179
#define IDC_GEOM_OPT                    1180
#define IDC_TITLE                       1181
#define IDC_AUTHOR                      1182
#define IDC_SUBJECT                     1183
#define IDC_KEYWORDS                    1184
#define IDC_CREATOR                     1185
#define IDC_PRODUCER                    1186
#define IDC_EDIT_PAPER_WIDTH            1187
#define IDC_EDIT_PAPER_HEIGHT           1188
#define IDC_RADIO_ACTIVE                1189
#define IDC_RADIO_ALL                   1190
#define IDC_EMEDDED_OPTIMIZED           1191
#define IDC_EDIT_PAPER_HEIGHT2          1192
#define IDC_EDIT_HATCH_DPI              1192
#define IDC_PS_GENERAL_STATIC_FILE_NAME 1193
#define IDC_EDIT_GEOM_DPI               1193
#define IDC_PS_GENERAL_EDIT_DESCRIPTION 1194
#define IDC_EDIT_COLOR_IMAGES_DPI       1194
#define IDC_PS_GENERAL_STATIC_FILE_INFO 1195
#define IDC_EDIT_BW_IMAGES_DPI          1195
#define IDC_PS_GENERAL_CHECK_SCALE_FACTOR 1196
#define IDC_PS_GENERAL_EDIT_SCALE_FACTOR 1197
#define IDC_PS_GENERAL_STATIC_SCALE_FACTOR 1198
#define IDC_PS_GENERAL_STATIC_DESCRIPTION 1199
#define IDC_PS_GENERAL_STATIC_TABLE_NAME 1200
#define IDC_PS_GENERAL_STATIC_NUMBER_STYLE 1201
#define IDC_PS_GENERAL_STATIC_PATH      1202
#define IDC_PS_GENERAL_STATIC_VERSION   1203
#define IDC_PS_GENERAL_STATIC_REGULAR   1204
#define IDC_PS_FORMVIEW_STATIC_STYLES   1205
#define IDC_PS_FORMVIEW_LIST_STYLES     1207
#define IDC_PS_FORMVIEW_STATIC_DESCRIPTION 1208
#define IDC__PS_FORMVIEW_STATIC_PROPERTIES 1209
#define IDC_PS_FORMVIEW_EDIT_DESCRIPTION 1210
#define IDC_PS_FORMVIEW_STATIC_COLOR    1211
#define IDC_PS_FORMVIEW_STATIC_DITHER   1212
#define IDC_PS_FORMVIEW_STATIC_GRAYSCALE 1213
#define IDC_PS_FORMVIEW_STATIC_PEN      1214
#define IDC_PS_FORMVIEW_STATIC_VIRTPEN  1215
#define IDC_PS_FORMVIEW_STATIC_SCREENING 1216
#define IDC_PS_FORMVIEW_STATIC_LINETYPE 1217
#define IDC_PS_FORMVIEW_STATIC_ADAPTIVE 1218
#define IDC_PS_FORMVIEW_STATIC_LINEWEIGHT 1219
#define IDC_PS_FORMVIEW_STATIC_LINESTYLE 1220
#define IDC_PS_FORMVIEW_STATIC_LINEJOINSTYLE 1221
#define IDC_PS_FORMVIEW_STATIC_FILLSTYLE 1222
#define IDC_PS_FORMVIEW_COMBO_COLOR     1223
#define IDC_PS_FORMVIEW_BTN_LINEWEIGHT  1224
#define IDC_PS_FORMVIEW_BTN_DELSTYLE    1225
#define IDC_PS_FORMVIEW_BTN_ADDSTYLE    1226
#define IDC_PS_FORMVIEW_BTN_SAVE        1227
#define IDC_PS_FORMVIEW_COMBO_DITHER    1228
#define IDC_PS_FORMVIEW_COMBO_GRAYSCALE 1229
#define IDC_PS_FORMVIEW_COMBO_ADAPTIVE  1230
#define IDC_PS_FORMVIEW_COMBO_LINETYPE  1233
#define IDC_PS_FORMVIEW_COMBO_LINEWEIGHT 1234
#define IDC_PS_FORMVIEW_COMBO_LINEENDSTYLE 1235
#define IDC_PS_FORMVIEW_COMBO_LINEJOINSTYLE 1236
#define IDC_PS_FORMVIEW_COMBO_FILLSTYLE 1237
#define IDC_PS_FORMVIEW_SPIN_PEN        1238
#define IDC_PS_FORMVIEW_SPIN_VIRTPEN    1239
#define IDC_PS_FORMVIEW_EDIT_SCREENING  1240
#define IDC_PS_FORMVIEW_SPIN_SCREENING  1241
#define IDC_PS_FORMVIEW_EDIT_PEN        1242
#define IDC_PS_GENERAL_STATIC_FILEPATH  1243
#define IDC_ZOOM                        1244
#define IDC_PS_ADDPS_STATIC_PSNAME      1244
#define IDC_PS_ADDPS_EDIT_PSNAME        1245
#define IDC_LAYERS                      1245
#define IDC_PS_ADDPS_STATIC_DINFO       1246
#define IDC_LAYERS2                     1246
#define IDC_ENCODED                     1246
#define IDC_PS_ADDPS_STATIC_SINFO       1247
#define IDC_ENCODED2                    1248
#define IDC_PS_GENERAL_STATIC_BITMAP    1249
#define IDC_PRC                         1249
#define IDC_PS_EDITLINEWEIGHT_LIST_LINEWEIGHTS 1250
#define IDC_PRC2                        1250
#define IDC_PRC3                        1251
#define IDC_PS_EDITLINEWEIGHT_BUTTON_EDITLINEWEIGHT 1251
#define IDC_PS_EDITLINEWEIGHT_BUTTON_MILLIMETERS 1252
#define IDC_HYPERLINK                   1252
#define IDC_PS_EDITLINEWEIGHT_BUTTON_INCHES 1253
#define IDC_TRANSPARENCY                1253
#define IDC_PS_EDITLINEWEIGHT_STATIC_LINEWEIGHTS 1254
#define IDC_PS_EDITLINEWEIGHT_BUTTON_SORTLINEWEIGHT 1255
#define IDC_PS_EDITLINEWEIGHT_STATIC_UNITSFORLISTING 1256
#define IDC_BUTTON_WINDOW               1257
#define IDC_CHECK_CENTERTHEPLOT         1258
#define IDC_CHECK_FIT_TO_PAPER          1259
#define IDC_CHECK_SCALE_LW              1260
#define IDC_CHECK_UPSIDEDOWN            1261
#define IDC_CHECK_PLOT_OBJECT_LW        1262
#define IDC_CHECK_HIDE_PAPERSPACE_OBJECTS 1263
#define IDC_CHECK_PLOT_WITH_PLOTSTYLES  1264
#define IDC_CHECK_PLOT_PAPERSPACE_LAST  1265
#define IDC_PIO_YY                      1266
#define IDC_PIO_X                       1267
#define IDC_PIO_XX                      1267
#define IDC_COMBO1                      1268
#define IDC_PAGESETUP_COMBO_PLOTSTYLEFILES 1268
#define IDC_PAGESETUP_BUTTON_PLOTSTYLEFILES 1269
#define IDC_COMBO_V_TILING              1269
#define IDC_MARGINS_L                   1270
#define IDC_MARGINS_R                   1271
#define IDC_MARGINS_T                   1272
#define IDC_PIO_YY3                     1273
#define IDC_MARGINS_B                   1273
#define IDC_CANONICAL_PAPER             1274
#define IDC_PAGESETUP_QUALITY           1275
#define IDC_CHECK_DISPLAY_PLOT_STYLES   1276
#define IDC_OFFLAYERS                   1276
#define IDC_WINDOW_MINX                 1277
#define IDC_WINDOW_MINY                 1278
#define IDC_WINDOW_MAXX                 1279
#define IDC_MARGINS_B2                  1280
#define IDC_WINDOW_MAXY                 1280
#define IDC_CHECK_PLOT_TRANSPARENCIES   1281
#define IDC_COMBO_MM_INCHES             1282
#define IDC_BUTTON_BROWSE               1283
#define IDC_EDIT_FILENAME               1284
#define IDC_DU_PROPERTIES               1285
#define IDC_LIST_SHEETS                 1286
#define IDC_LIST2                       1289
#define IDC_LIST_LAYER                  1289
#define IDC_SDWFSHEETNAME               1290
#define IDC_GBDGNUNITS                  1291
#define IDC_RBDGNUNITS1                 1292
#define IDC_RBDGNUNITS2                 1293
#define IDC_HLR                         1293
#define IDC_DELETE                      1294
#define IDC_COPY                        1295
#define IDC_NEW                         1296
#define IDC_FROM_TEMPLATE               1297
#define IDC_GRADCOLOR_RED               1298
#define IDC_GRADCOLOR_GREEN             1299
#define IDC_PREVIEW                     1299
#define IDC_GRADCOLOR_SELECTED          1300
#define IDC_GRADCOLOR_BLUE              1301
#define IDC_GRADCOLOR_CHOOSE            1302
#define IDC_EX_MONO_CHECK               1303
#define IDC_ENABLE_OUTPUT_CHECK         1305
#define IDC_BLOCKS_LIST                 1306
#define IDC_UNDO_DELETE_BLOCK           1307
#define IDC_DELETE_BLOCK                1308
#define IDC_HIDDEN_BLOCK_LIST           1309
#define IDC_HIDE                        1310
#define IDC_HIDE_ALL_BLOCKS             1311
#define IDC_BUTTON2                     1312
#define IDC_PREVIEW_WINDOW              1312
#define IDC_BHIGHLIGHT                  1312
#define IDC_BUTTON_ADD_BRANCH           1312
#define IDC_TEXTURE_PATH_BTN            1312
#define IDC_STATIC_PREVIEW              1313
#define IDC_MERGE_REVERT                1313
#define IDPREVIEWUPDATE                 1314
#define IDC_MERGE_FULL_THEIR            1314
#define IDC_SLOWMODE                    1315
#define IDC_SYSLINK2                    1318
#define IDC_URL                         1320
#define IDC_ODAICON                     1321
#define IDC_URL3                        1322
#define IDC_LBVIEWS                     1322
#define IDC_URL2                        1323
#define IDC_SPREVIEW                    1323
#define IDC_SWIDTH                      1324
#define IDC_SHEIGHT                     1325
#define IDC_SBPP                        1326
#define IDC_CBVIEWEXTENTS               1327
#define IDC_SPOSITION                   1328
#define IDC_STARGET                     1329
#define IDC_CBON                        1330
#define IDC_CBTARGETED                  1331
#define IDC_EINTENSITY                  1332
#define IDC_SCOLOR                      1333
#define IDC_BCOLOR                      1334
#define IDC_EHOTSPOT                    1335
#define IDC_LBMATERIALS                 1335
#define IDC_EFALLOFF                    1336
#define IDC_CBDIAGBKGND                 1336
#define IDC_SAMBIENT                    1337
#define IDC_BAMBIENT                    1338
#define IDC_SDIFFUSE                    1339
#define IDC_BDIFFUSE                    1340
#define IDC_SSPECULAR                   1341
#define IDC_BSPECULAR                   1342
#define IDC_SDIFFUSEMAP                 1343
#define IDC_SGLOSS                      1344
#define IDC_SOPACITY                    1345
#define IDC_SSELFILLUMINATION           1346
#define IDC_SNAME                       1347
#define IDC_SDESCRIPTION                1348
#define IDC_CBDEVICE                    1349
#define IDC_VECTPROPS_LIST              1350
#define IDC_EVALUE                      1351
#define IDC_RBTRUE                      1352
#define IDC_RBFALSE                     1353
#define IDC_PDFEXPORT_HATCHEXPTYPE      1354
#define IDC_PDFEXPORT_OTHERHATCHEXPTYPE 1355
#define IDC_JUSTIFY                     1356
#define IDC_TEXT                        1357
#define IDC_EDIT2                       1358
#define IDC_HEIGHT                      1358
#define IDC_EDIT_NAME                   1358
#define IDC_ANGLE                       1359
#define IDC_EDIT_WIDTH                  1359
#define IDC_ANGLE_ST                    1360
#define IDC_EDIT_HEIGHT                 1360
#define IDC_JUSTIFY2                    1361
#define IDC_STYLE                       1361
#define IDC_EDIT_TMARGIN                1361
#define IDC_EDIT_BMARGIN                1362
#define IDC_EDIT_LMARGIN                1363
#define IDC_EDIT_HEIGHT3                1364
#define IDC_EDIT_RMARGIN                1364
#define IDC_COMBO_MUNITS                1365
#define IDC_BUTTON_ADD_MEDIA            1366
#define IDC_RADIO_FPATH                 1367
#define IDC_RADIO_RPATH                 1368
#define IDC_RADIO_NPATH                 1369
#define IDC_STATIC_PATH2SAVE            1370
#define IDC_STATIC_P2S                  1371
#define IDC_STATIC_PATH_TYPE            1372
#define IDC_BUTTON_CUSTOM_PROPERTIES    1373
#define IDC_LAYOUTPREVIEW               1374
#define IDC_TEXT_SEARCHABLE             1375
#define IDC_PDFEXPORT_COLOR_POLICY      1376
#define IDC_PDFEXPORT_GRADIENTHATCHEXPTYPE 1377
#define IDC_CROP                        1378
#define IDC_DCT                         1379
#define IDC_SLIDER_QUALITY              1380
#define IDC_STATIC_IQ                   1381
#define IDC_PRC_COMPRESSION             1382
#define IDC_STATIC_PRC_COMPRESSION      1383
#define IDC_LBVISUALSTYLES              1384
#define IDC_VSPROPS_LIST                1385
#define IDC_RBBYLAYER                   1386
#define IDC_RBBYBLOCK                   1387
#define IDC_RBBYCOLOR                   1388
#define IDC_RBBYACI                     1389
#define IDC_RBBYPEN                     1390
#define IDC_RBFOREGROUND                1391
#define IDC_RBBYDGNINDEX                1392
#define IDC_RBNONE                      1393
#define IDC_LINEARIZED                  1394
#define IDC_VIEWPORT_BORDERS            1395
#define IDC_COMBO_MERGE_CONTROL         1396
#define IDC_UNDOLIST                    1397
#define IDC_COMBO_PDF_A                 1398
#define IDC_BFBX                        1399
#define IDC_LIST_BRANCHES               1400
#define IDC_EDIT_ADD_BRANCH             1401
#define IDC_CHECK_DIFF_DEV              1402
#define IDC_CHECK_DIFF_BYOBJECT         1403
#define IDC_SPROPNAME                   1404
#define IDC_RBPLACEHOLDER               1405
#define IDC_CBPLACEHOLDER               1406
#define IDC_MEASURING                   1407
#define IDC_LIST_LOG                    1408
#define IDC_USE_GS_CACHE                1409
#define IDC_SPLIT2                      1410
#define IDC_PRC_TESS_COMPRESSION        1411
#define IDC_CBSHOWINTERNAL              1412
#define IDC_TP_USENEWTESSELLATION       1413
#define IDC_TP_RECALCSURFTOL            1414
#define IDC_BUTTON_DEFAULT              1415
#define IDC_ADD_BRANCH                  1418
#define IDC_EDIT_CURRENT_BRANCH         1419
#define IDC_BUTTON_SWITCH_BRANCH        1420
#define IDC_LIST_MERGE_BRANCHES_1       1421
#define IDC_LIST_MERGE_BRANCHES_2       1422
#define ID_BUTTON_MERGE_OK              1423
#define IDC_CBENABLEENVIMAGE            1424
#define IDC_SENVIMAGESTATUS             1425
#define IDC_SENVIMAGEFILE               1426
#define IDC_CBENABLEENVFOG              1427
#define IDC_CBENABLEENVFOGBACKGROUND    1428
#define IDC_SENVFOGCOLOR                1429
#define IDC_BENVFOGCOLOR                1430
#define IDC_SENVFOGDISTNEAR             1431
#define IDC_BENVFOGDISTNEAR             1432
#define IDC_SENVFOGDISTFAR              1433
#define IDC_BENVFOGDISTFAR              1434
#define IDC_SENVFOGDENSNEAR             1435
#define IDC_BENVFOGDENSNEAR             1436
#define IDC_SENVFOGDENSFAR              1437
#define IDC_BENVFOGDENSFAR              1438
#define IDC_SENVIMAGEPREVIEW            1439
#define IDC_EDIT_BBERRORS               1440
#define IDC_EDIT_TR00                   1445
#define IDC_TRANSFORM_APPLY_BTN         1446
#define IDC_COMBO_H_TILING              1447
#define IDC_TEXTURE_PATH                1448
#define IDC_TEXTURE_PREVIEW             1449
#define IDC_STATIC_TEXTURE              1450
#define IDC_BTN_CLASSES_DUMP            1451
#define IDC_BOMLIST                     1452
#define IDC_BOMROW_TABLE                1453
#define IDC_BOMLIST_TEXT                1454
#define IDC_BOMROWS_TEXT                1455
#define IDC_BOM_PROP_TEXT               1456
#define IDC_BOM_PROP_TYPE               1457
#define IDC_MECHBOM_SETTINGS_ALLPROPS   1458
#define IDC_MECH_BOM_SETTINGS_ADDTO     1459
#define IDC_MECHBOM_SETTINGS_ALLTEXT    1460
#define IDC_MECHBOM_SETTINGS_VISIBLETEXT 1461
#define IDC_MECH_BOM_SETTINGS_BUTTON    1462
#define IDC_MECH_STRUCTURE_MODELTEXT    1463
#define IDC_STRUCTURE_TREE              1464
#define IDC_MECHSTD_MEASUREMENT         1465
#define IDC_MECHSTD_CURRSTDNAME         1466
#define IDC_MECHSTD_SYMBSTDTREE         1467
#define IDC_MECHSTD_ALLSTDSLIST         1468
#define IDC_MECHSTD_DIMSTYLEBOX         1469
#define IDC_MECHSTD_TXTSTYLEBOX         1470
#define IDC_MECHSTD_TXTHEIGHTBOX        1471
#define IDC_MECHSTD_ARROWTYPEBOX        1472
#define IDC_MECHSTD_ARROWSIZEBOX        1473
#define IDC_MECHSTD_ARROWCOLORBOX       1474
#define IDC_MECHSTD_SYMBOLATTACHBOX     1475
#define IDC_MECHSTD_SYMBOLCOLORBOX      1476
#define IDC_MECHSTD_TEXTCOLORBOX        1477
#define IDC_MECHSTD_FIRSTANGLE          1478
#define IDC_MECHSTD_THIRDANGLE          1479
#define IDC_MECHSTD_SYMBOLGRADCOLOR     1480
#define IDC_MECHSTD_LEADERGRADCOLOR     1481
#define IDC_MECHSTD_TEXTGRADCOLOR       1482
#define IDC_MECH_BOMMGR_EXPALL          1483
#define IDC_MECH_BOMMGR_COLALL          1484
#define IDC_BOM_VIEW_TXT                1485
#define IDC_BOM_VIEW_COMBO              1486
#define IDC_BOM_EXPCOLLAPSE             1487
#define IDC_BOM_ITEM_NUM                1488
#define IDC_MECHBOM_SETTINGS_VISIBLEPROPS 1489
#define IDC_BOM_PROPS_VALUE             1490
#define IDC_DISABLE_GS                  1491
#define IDC_TRANSPARENT_BG              1492
#define IDC_WATERMARK                   1493
#define IDC_COMBO_WM_FONT               1494
#define IDC_EDIT_WM_OPACITY             1495
#define IDC_COMBO_WM_FONT_COLOR         1496
#define IDC_COMBO_WM_POSITION           1497
#define IDC_CHECK_FIT_WM_2_PAGE         1498
#define IDC_EDIT_WM_FONTSIZE            1499
#define IDC_BUTTON_LAYER_STATES         1500
#define IDC_LIST1                       1501
#define IDC_COMBO_SHADED_VP_HANDLE      1502
#define IDC_UPSCALE_IMAGES              1503
#define IDC_RADIO_DB_ACTIVE             1504
#define IDC_RADIO_DB_ALL                1505
#define IDC_STATIC_EXPORT_DBS           1506
#define IDC_TEXT_SEARCHABLE_CTRL_F      1507
#define IDC_SEARCHABLE_TXT_ON_SHADED_VP 1508
#define IDC_USE_PDF_BLOCKS              1509
#define IDC_MERGE_BMP1                  1510
#define IDC_MERGE_BMP2                  1511
#define IDC_MERGE_FULL_MINE             1512
#define IDC_MERGE_PREFER_MINE           1513
#define IDC_MERGE_PREFER_THEIR          1514
#define IDC_CHECK_MERGE_MANUAL          1515
#define IDC_MERGE_BMP_ANCESTOR          1516
#define IDC_MERGE_TEXT_MINE             1517
#define IDC_MERGE_TEXT_ANCESTOR         1518
#define IDC_MERGE_TEXT_THEIR            1519
#define IDC_EDIT_TEXT                   1520
#define IDC_BUTTON_EDIT_TEXT_OK         1521
#define ID_VIEW_CLASSESINFO             32771
#define ID_FILE_PARTIAL_OPEN            32772
#define ID_PROPERTIES                   32773
#define ID_VIEW_SUMMINFO                32774
#define ID_REFRESH                      32776
#define ID_VIEW_SCHEMA                  32777
#define ID_VIEW_DXF                     32778
#define ID_VIEW_DWG                     32779
#define ID_EDIT_PURGE                   32780
#define ID_PURGE_ALL                    32783
#define ID_PURGE_LAYERS                 32784
#define ID_PURGE_LTYPES                 32785
#define ID_PURGE_TEXT_STYLES            32786
#define ID_PURGE_DIM_STYLES             32787
#define ID_PURGE_BLOCKS                 32788
#define ID_EDIT_RUNDEBUGCOMMAND         32789
#define ID_EXPLODE_ALL                  32790
#define ID_EDIT_AUDIT                   32791
#define ID_VIEW_SYSTEMVARIABLES         32792
#define ID_EDIT_ADDEXAMPLECUSTOMOBJECT  32793
#define ID_FILE_RECOVER                 32794
#define ID_VIEW_SETACTIVELAYOUT         32796
#define ID_BUTTON_ZOOMEXTENTS           32798
#define ID_EDIT_ZOOMEXTENTS             32799
#define ID_EDIT_IDEDITLINETYPE          32800
#define ID_EDIT_RECOMPUTEDIMBLOCK       32801
#define ID_OPTIONS_SAVEROUNDTRIPDATA    32802
#define ID_VIEW_XREF_TREE               32803
#define ID_PREVIEW_FILE                 32804
#define ID_BUTTON_SAVEASR12DWG          32805
#define ID_VIEW_ZOOMOUT                 32809
#define ID_VIEW_PAN                     32811
#define ID_OPTIONS_DOUBLEBUFFER         32812
#define ID_WINDOW_RENDER                32813
#define ID_VIEW_ZOOMEXTENTS             32813
#define ID_VIEW_ZOOM_WINDOW             32814
#define ID_TOOLS_LOADAPPLICATIONS       32815
#define ID_VIEW_ROTATEZ                 32818
#define ID_VIEW_ROTATEX                 32820
#define ID_VIEW_ROTATEY                 32821
#define ID_FILE_EXPORT                  32822
#define ID_FILE_PUBLISH                 32823
#define ID_VIEW_RENDER_MATERIALS        32824
#define ID_VIEW_RENDER_LIGTH            32825
#define ID_VIEW_RENDER_LIGHT            32826
#define ID_OPTIONS_TRIANGULATION_PARAMS 32827
#define ID_FILE_BMPEXPORT               32829
#define ID_FORMAT_LAYER                 32830
#define ID_OPTIONS_SAVEPREVIEW          32831
#define ID_FORMAT_BACKGROUNDCOLOR       32832
#define ID_EDIT_ACIS_CONVERSION         32833
#define ID_OPENGL_WIREFRAME             32834
#define ID_APPEND_LINE                  32835
#define ID_OPTIONS_USEGSMODELGEOMETRYCACHE 32836
#define ID_FORMAT_LINEWEIGHTSETTINGS    32837
#define ID_VIEW_NAMEDVIEWS              32838
#define ID_XRM_LIST                     32839
#define ID_XRM_TREE                     32840
#define ID_VIEW_FILEDEPENDENCY          32841
#define ID_INSERT_EXTERNALREFERENCE     32842
#define ID_FILE_IMPORT_DWF              32843
#define ID_INSERT_XREFMANAGER           32844
#define ID_VECTORIZE                    32845
#define ID_FILE_EXPORT_SVG              32846
#define ID_DRAG                         32848
#define ID_OPTIONS_SAVEWITHPASSWORD     32852
#define ID_EDIT_ACIS_SAT_SAVE           32853
#define ID_2DWIREFRAME                  32864
#define ID_3DWIREFRAME                  32865
#define ID_HIDDEN                       32866
#define ID_FLAT_SHADED                  32867
#define ID_GOURAUD_SHADED               32868
#define ID_FLAT_SHADED_WITH_EDGES       32869
#define ID_GOURAUD_SHADED_EDGES_ON      32870
#define ID_EDIT_CONSOLE                 32871
#define ID_OPTIONS_FILL_TTF             32872
#define ID_VIEWER_REGEN                 32873
#define ID_EDIT_REDUCE                  32874
#define ID_VECTORIZE_ADDVECTORIZERDLL   32875
#define ID_VECTORIZE_CLEARMENU          32876
#define ID_VECTORIZER_FIRST             32877
#define ID_VECTORIZER_LAST              32887
#define ID_EDIT_RECENTCOMMAND           32888
#define ID_OPTIONS_SNAPPING             32889
#define ID_EDIT_ENTGET                  32890
#define ID_TOOLS_OPTIONS_SETFACETRES    32891
#define ID_VIEWER_VPREGEN               32892
#define ID_EDIT_FINDNEXTSELECTED        32893
#define ID_INSERT_OLEOBJECT             32894
#define ID_FILE_EXPORT_PDF              32895
#define ID_FILE_3DPUBLISH               32896
#define ID_FORMAT_LINETYPE              32897
#define ID_FORMAT_MLSTYLE               32898
#define ID_OPTIONS_SOFTHLR              32899
#define ID_OPTIONS_DISCARDBACKFACES     32900
#define ID_FILE_PAGE_SETUP_MANAGER      32901
#define ID_FILE_PLOT_STYLE_MANAGER      32902
#define ID_WINDOW_SELECT                32904
#define ID_BUTTON32905                  32905
#define ID_CROSSING_SELECT              32906
#define ID_BUTTON32907                  32907
#define ID_FENCE_SELECT                 32908
#define ID_VIEW_3DORBIT                 32909
#define ID_OPTIONS_PRINT                32910
#define ID_BUTTON32911                  32911
#define ID_OPTIONS_PRINTPREVIEW         32912
#define ID_OPTIONS_GDITRANSPARENCY      32913
#define ID_VP_OVR_CLEAR_ALL_FOR_CURR_VP 32914
#define ID_VP_OVR_REMOVE_COLOR          32917
#define ID_VP_OVR_REMOVE_LINETYPE       32918
#define ID_VP_OVR_REMOVE_LINEWEIGHT     32919
#define ID_VP_OVR_REMOVE_PLOTSTYLE      32920
#define ID_VP_OVR_CLEAR_ALL_FOR_ALL_VP  32921
#define ID_INSERT_DWFUNDERLAY           32922
#define ID_INSERT_DGNUNDERLAY           32923
#define ID_TOOLS_MACRO_VISUALBASICEDITOR 32924
#define ID_EDIT_CLEARSELECTION          32925
#define ID_FILE_EXPORT_HOOPS            32927
#define ID_VIEW_RENDER_ENVIRONMENT      32928
#define ID_3DVIEWS_TOP                  32929
#define ID_3DVIEWS_BOTTOM               32930
#define ID_3DVIEWS_LEFT                 32931
#define ID_3DVIEWS_RIGHT                32932
#define ID_3DVIEWS_FRONT                32933
#define ID_3DVIEWS_BACK                 32934
#define ID_DEBUG_GEOMETRY               32935
#define ID_INSERT_PDFUNDERLAY           32936
#define ID_OPTIONS_BLOCKSCACHE          32937
#define ID_VP_OVR_REMOVE_TRANSPARENCY   32938
#define ID_VIEW_ANNOTATIONSCALE         32939
#define ID_ANNOTATIONSCALE_CUSTOM       32940
#define ID_OPTIONS_DISABLE_ANNOTATIONS  32941
#define ID_OPTIONS_GSDEVMT              32942
#define ID_FILE_IMPORT_PDF              32943
#define ID_FILE_MT_OPEN                 32944
#define ID_VIEW_RENDER_VECTPROPS        32945
#define ID_OPTIONS_CONTEXTCOLORS        32946
#define ID_OPTIONS_TTFPOLYDRAW          32947
#define ID_FILE_EXPORT_COLLADA          32948
#define ID_FILE_IMPORT_COLLADA          32949
#define ID_OPTIONS_TTFTEXTOUT           32950
#define ID_TOOLS_DRAWINGOPTIONS         32951
#define ID_OPTIONS_USEUNLOADPAGING      32954
#define ID_OPTIONS_USEFILEPAGING        32955
#define ID_TOOLS_OPTIONS                32956
#define ID_VIEW_RENDER_SNAPSHOT         32957
#define ID_VIEW_RENDER_DBLIGHTS         32958
#define ID_VIEW_RENDER_DBMATERIALS      32959
#define ID_OPTIONS_USETEMPUNDOFILES     32960
#define ID_OPTIONS_NUMREGENTHREADS      32961
#define ID_OPTIONS_DYNAMICSUBENTHLT     32962
#define ID_VIEW_CONSTRDISPLAY           32963
#define ID_OPTIONS_GRADASBITMAP         32964
#define ID_OPTIONS_GRADASPOLYS          32965
#define ID_OPTIONS_GRADASPOLYSTHRESHOLD 32966
#define ID_OPTIONS_TTFCACHE             32967
#define ID_APPEND_CIRCLE                32968
#define ID_APPEND_TEXT                  32971
#define ID_3DVIEWS_SW                   32972
#define ID_3DVIEWS_SE                   32973
#define ID_3DVIEWS_NE                   32974
#define ID_3DVIEWS_NW                   32975
#define ID_VIEW_RENDER_DBVISUALSTYLES   32976
#define ID_OPTIONS_USEHISTORYFILE       32977
#define ID_UNDO_LIST                    32978
#define ID_UPDATE_CHANGES               32979
#define ID_COMMIT_CHANGES               32980
#define ID_REDO_LIST                    32981
#define ID_VIEW_RENDER_TAKESNAPSHOT     32982
#define ID_VIEWER_REGEN_VISIBLE_ONLY    32983
#define ID_TOOLS_REVISIONLOG            32984
#define ID_VIEW_DISABLEAUTOREGEN        32985
#define IDD_PDF_IMPORT_DIALOG           32986
#define IDC_PDF_AS_BLOCK                32987
#define IDC_PDF_JOIN_LINE_ARC           32988
#define IDC_EDIT_PAGE_NUM               32989
#define IDC_PDF_CONVERT_SOLIDS2HATCHES  32990
#define IDC_PDF_LINEWEIGHT              32991
#define IDC_INSERTION_POINT             32992
#define IDC_STATIC_PAGE_COUNT           32993
#define IDC_EDIT_SCALE                  32994
#define IDC_PDF_PAGE_ROTAION            32995
#define IDC_PDF_IMP_VECTOR_GEOM         32996
#define IDC_PDF_IMP_TT_TEXT             32997
#define IDC_PDF_IMP_SOLID_FILLS         32998
#define IDC_PDF_IMP_RASTER_IMAGES       32999
#define IDC_PDF_IMP_SHADING             33000
#define IDC_RADIO_USE_PDF_LAYERS        33001
#define IDC_RADIO_PDF_CREATE_OBJ_LAYER  33002
#define IDC_RADIO_PDF_USE_CUR_LAYER     33003
#define IDC_STATIC_DATA_TO_IMPORT       33004
#define IDC_STATIC_LAYER                33005
#define IDC_STATIC_IMP_OPTIONS          33006
#define IDC_PDF_IMP_USE_2DGEOM_OPTIM    33007
#define ID_BUTTON33007                  33008
#define ID_PUSH_CHANGES                 33009
#define ID_SWITCH_BRANCH                33010
#define ID_MERGE_BRANCH                 33011
#define ID_PARTREF_BUTTON               33012
#define ID_BALLOON_BUTTON               33013
#define ID_STANDARD_BUTTON              33015
#define ID_SURFSYM_BUTTON               33016
#define ID_PLIST_BUTTON                 33017
#define ID_BOM_BUTTON                   33018
#define ID_MECH_STRUCT_BUTTON           33019
#define ID_NEWCOMPONENT_NEWINSTANCE     33020
#define ID_NEWCOMPONENT_REMOVE          33021
#define ID_NEW_COMPONENT                33022
#define ID_NEW_INSTANCE                 33023
#define ID_COMPONENTS_RENAME            33024
#define ID_MECHSTD_OLDNAMETXT           33025
#define ID_MECHSTD_NEWNAMETXT           33026
#define ID_MECHSTD_SETTINGS             33027
#define ID_MECHSTD_REMOVESYMBSTD        33028
#define ID_MECHSTD_CREATE               33029
#define ID_MECHSTD_COPY                 33030
#define ID_MECHSTD_RENAME               33031
#define ID_MECHSTD_REMOVE               33032
#define ID_MECH_STDMGR_SETTINGS         33033
#define ID_MECH_STDMGR_REMOVE           33034
#define ID_MECH_STDMGR_RESTOREDEFAULTS  33035
#define ID_MECH_NEWSTD_BASENAME         33036
#define ID_MECH_NEWSTD_BASENAMEBOX      33037
#define ID_MECH_NEWSTD_ISCUSTOM         33038
#define ID_MECH_NEWSTD_CUSTOMNAME       33039
#define ID_MECH_NEWSTD_CUSTOMNAMEEDIT   33040
#define ID_MECH_STDMGR_LINKTODIMSTYLE   33041
#define ID_MECH_STDMGR_LINKTODIMLEADER  33042
#define ID_MECHSYMBOLS_BUTTON           33043
#define ID_EDGESYM_BUTTON               33044
#define ID_TAPERSYM_BUTTON              33045
#define ID_WELDSYM_BUTTON               33046
#define ID_NOTESYM_BUTTON               33047
#define ID_FCFSYM_BUTTON                33048
#define ID_DATUMIDSYM_BUTTON            33049
#define ID_FEATIDSYM_BUTTON             33050
#define ID_SECTIONLINE_BUTTON           33051
#define ID_DETAILSYM_BUTTON             33052
#define ID_DATUMTGT_NONE_BUTTON         33053
#define ID_DATUMTGT_POINT_BUTTON        33054
#define ID_DATUMTGT_LINE_BUTTON         33055
#define ID_DATUMTGT_CIRCLE_BUTTON       33056
#define ID_DATUMTGT_RECTANGLE_BUTTON    33057
#define ID_DATUMTGT_ATTACHED_BUTTON     33058
#define ID_HOLECHART_BUTTON             33059
#define ID_SYMBOL_HOLECHART             33060
#define ID_OPTIONS_DWF_EXPORT_MODEL_EXT 33061
#define ID_OPTIONS_DISABLEFIELDUPDATEONLOAD 33062
#define ID_OPTIONS_TTFTRIANGLECACHE     33063
#define ID_FILE_EXPORTTOIFC             33064
#define IDC_PDF_IMP_TYPE3_AS_TT         33065
#define IDC_PDF_IMP_AS_RGB              33066
#define ID_OPTIONS_DONOTEVALUATEASSOC   33067
#define IDC_INVALID_TTF_AS_GEOM         33068
#define IDC_PDF_IMP_USE_CLIPPING        33069
#define IDC_PDF_IMP_PAGE_BRD_CLIPPING   33070
#define IDC_PDF_IMP_NEED_TO_COMB_TEXT   33071
#define IDC_PDF_IMP_USE_PDF_TRANSPARENT 33072
#define IDC_PDF_IMP_STATIC_HYPER_METH   33073
#define IDC_PDF_IMP_RADIO_HYPER_AS_ENTITY 33074
#define IDC_STATIC_HYPER_IMPORT         33075
#define IDC_USE_INSUNITS                33076
#define IDC_PDF_IMP_WIDGETS             33077
#define IDC_PDF_IMP_USE_IMG_CLIPPING    33078
#define IDC_STATIC_PAGE_SIZE            33079
#define IDC_STATIC_SCALE_TEXT           33080
#define IDC_PDFIMPORT_TEXT_OPTIION_BUTTON 33081
#define IDC_STATIC_MAIN_PDFIMPORT_TEXT_OPT 33082
#define IDC_STATIC_PDFIMPORT_CHANGE_FONT_OPT 33083
#define IDC_PDFIMPORT_CHANGE_NOTFOUND_FONT 33084
#define IDC_PDFIMPORT_CHANGE_NF_COMBO   33085
#define IDC_PDFIMPORT_CHANGE_TYPE3_FONT2 33086
#define IDC_PDFIMPORT_CHANGE_T3_COMBO2  33087
#define IDC_PDFIMPORT_CHANGE_T3_COMBO   33088
#define IDC_PDFIMPORT_FCHANGE_COMBO1    33089
#define IDC_PDFIMPORT_FCHANGE_COMBO2    33090
#define IDC_PDFIMPORT_FCHANGE_COMBO3    33091
#define IDC_PDFIMPORT_CHANGE_FONT1      33092
#define IDC_PDFIMPORT_CHANGE_FONT2      33093
#define IDC_PDFIMPORT_CHANGE_FONT3      33094
#define IDC_EDIT_PDFIMPORT_FN1          33095
#define IDC_EDIT_PDFIMPORT_FF1          33096
#define IDC_EDIT_PDFIMPORT_FN2          33097
#define IDC_EDIT_PDFIMPORT_FF2          33098
#define IDC_EDIT_PDFIMPORT_FN3          33099
#define IDC_EDIT_PDFIMPORT_FF3          33100
#define IDD_PDF_IMPORT_TEXT_OPT_DIALOG  33101
#define IDC_PDF_IMPORT_EXTRACT_EMBEDD_FONTS 33102
#define IDC_PDF_IMPORT_TRY_FIX_UT       33103
#define ID_EDIT_EDITTEXT                33104
#define IDC_PDF_EXPORT_USE_MT_VECT      33105
#define IDC_BUTTON_PDF_SECURITY         33106
#define IDD_PDF_SECURITY_DIALOG         33107
#define IDC_EDIT_USER_PASSWORD          33108
#define IDC_EDIT_OWNER_PASSWORD         33109
#define IDC_PDF_SC_ALLOW_EXTRACT        33110
#define IDC_PDF_SC_ALLOW_ASSEMBLE       33111
#define IDC_PDF_SC_ALLOW_ANNOTATE       33112
#define IDC_PDF_SC_ALLOW_FORM_FILL      33113
#define IDC_PDF_SC_ALLOW_MODIFY         33114
#define IDC_PDF_SC_ALLOW_PRINT_ALL      33115
#define IDC_PDF_SC_ALLOW_PRINT_LOW      33116
#define ID_OPTIONS_GDIRASTERS           33117

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        290
#define _APS_NEXT_COMMAND_VALUE         33118
#define _APS_NEXT_CONTROL_VALUE         1522
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
