/////////////////////////////////////////////////////////////////////////////// 
// Copyright (C) 2002-2022, Open Design Alliance (the "Alliance"). 
// All rights reserved. 
// 
// This software and its documentation and related materials are owned by 
// the Alliance. The software may only be incorporated into application 
// programs owned by members of the Alliance, subject to a signed 
// Membership Agreement and Supplemental Software License Agreement with the
// Alliance. The structure and organization of this software are the valuable  
// trade secrets of the Alliance and its suppliers. The software is also 
// protected by copyright law and international treaty provisions. Application  
// programs incorporating this software must include the following statement 
// with their copyright notices:
//   
//   This application incorporates Open Design Alliance software pursuant to a license 
//   agreement with Open Design Alliance.
//   Open Design Alliance Copyright (C) 2002-2022 by Open Design Alliance. 
//   All rights reserved.
//
// By use of this software, its documentation or related materials, you 
// acknowledge and accept the above terms.
///////////////////////////////////////////////////////////////////////////////
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opendesign_android_TeighaDWGJni */

#ifndef _Included_com_opendesign_android_TeighaDWGJni
#define _Included_com_opendesign_android_TeighaDWGJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opendesign_android_TeighaDWGJni
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_init
  (JNIEnv *, jclass);

/*
 * Class:     com_opendesign_android_TeighaDWGJni
 * Method:    finit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_finit
  (JNIEnv *, jclass);

/*
 * Class:     com_opendesign_android_TeighaDWGJni
 * Method:    open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_opendesign_android_TeighaDWGJni
 * Method:    createRenderer
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_createRenderer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_opendesign_android_TeighaDWGJni
 * Method:    renderFrame
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_renderFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_opendesign_android_TeighaDWGJni
 * Method:    destroyRenderer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_destroyRenderer
  (JNIEnv *, jclass);

/*
 * Class:     com_opendesign_android_TeighaDWGJni
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_close
  (JNIEnv *, jclass);

/*
 * Class:     com_opendesign_android_TeighaDWGJni
 * Method:    viewTranslate
 * Signature: (FF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_viewTranslate
  (JNIEnv *, jclass, jfloat, jfloat);

/* Class:     com_opendesign_android_TeighaDWGJni
 * Method:    viewScale
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_viewScale
  (JNIEnv *, jclass, jfloat);

/* Class:     com_opendesign_android_TeighaDWGJni
 * Method:    viewCanRotate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_viewCanRotate
  (JNIEnv *, jclass);

/* Class:     com_opendesign_android_TeighaDWGJni
 * Method:    viewRotate
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_viewRotate
  (JNIEnv *, jclass, jfloat);

/* Class:     com_opendesign_android_TeighaDWGJni
 * Method:    viewOrbit
 * Signature: (FF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_viewOrbit
  (JNIEnv *, jclass, jfloat, jfloat);

/* Class:     com_opendesign_android_TeighaDWGJni
 * Method:    viewGetRenderMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_opendesign_android_TeighaDWGJni_viewGetRenderMode
  (JNIEnv *, jclass);

/* Class:     com_opendesign_android_TeighaDWGJni
 * Method:    viewSetRenderMode
 * Signature: (I)Z
 */
JNIEXPORT jint JNICALL Java_com_opendesign_android_TeighaDWGJni_viewSetRenderMode
  (JNIEnv *, jclass, jint);

/* Class:     com_opendesign_android_TeighaDWGJni
 * Method:    viewRegen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_viewRegen
  (JNIEnv *, jclass);

  /* Class:     com_opendesign_android_TeighaDWGJni
 * Method:    saveContext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_opendesign_android_TeighaDWGJni_saveContext
  (JNIEnv *, jclass, jinit);

#ifdef __cplusplus
}
#endif
#endif
